# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.avatar_presenter_list_response import AvatarPresenterListResponse
from ..types.tts_voice_list_response import TtsVoiceListResponse
from .raw_client import AsyncRawResourcesClient, RawResourcesClient


class ResourcesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawResourcesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawResourcesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawResourcesClient
        """
        return self._raw_client

    def list_avatar_presenters(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AvatarPresenterListResponse:
        """
        List available avatar presenters. Pass an `avatarPresenterId` from the response to the avatar video endpoint. Paginated; pass `nextCursor` from the previous response as `cursor` to fetch the next page.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum number of items to return in the page. Defaults to 50; capped at 200.

        cursor : typing.Optional[str]
            Opaque pagination cursor returned as `nextCursor` by the previous page. Omit on the first request. Cursors are tied to the endpoint that produced them and must be passed unmodified.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AvatarPresenterListResponse
            List of avatar presenters. Pass an `avatarPresenterId` to `POST /v1/tools/generate-avatar`.

        Examples
        --------
        from videogen import VideoGenApi

        client = VideoGenApi(
            token="YOUR_TOKEN",
        )
        client.resources.list_avatar_presenters()
        """
        _response = self._raw_client.list_avatar_presenters(limit=limit, cursor=cursor, request_options=request_options)
        return _response.data

    def list_tts_voices(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        include_deprecated_voices: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TtsVoiceListResponse:
        """
        List available text-to-speech voices. Pass a `voiceId` from the response to the text-to-speech endpoint. Paginated; pass `nextCursor` from the previous response as `cursor` to fetch the next page.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum number of items to return in the page. Defaults to 50; capped at 200.

        cursor : typing.Optional[str]
            Opaque pagination cursor returned as `nextCursor` by the previous page. Omit on the first request. Cursors are tied to the endpoint that produced them and must be passed unmodified.

        include_deprecated_voices : typing.Optional[bool]
            When true, includes voices that are deprecated but still callable. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TtsVoiceListResponse
            List of TTS voices. Pass a `voiceId` to `POST /v1/tools/text-to-speech`.

        Examples
        --------
        from videogen import VideoGenApi

        client = VideoGenApi(
            token="YOUR_TOKEN",
        )
        client.resources.list_tts_voices()
        """
        _response = self._raw_client.list_tts_voices(
            limit=limit,
            cursor=cursor,
            include_deprecated_voices=include_deprecated_voices,
            request_options=request_options,
        )
        return _response.data


class AsyncResourcesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawResourcesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawResourcesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawResourcesClient
        """
        return self._raw_client

    async def list_avatar_presenters(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AvatarPresenterListResponse:
        """
        List available avatar presenters. Pass an `avatarPresenterId` from the response to the avatar video endpoint. Paginated; pass `nextCursor` from the previous response as `cursor` to fetch the next page.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum number of items to return in the page. Defaults to 50; capped at 200.

        cursor : typing.Optional[str]
            Opaque pagination cursor returned as `nextCursor` by the previous page. Omit on the first request. Cursors are tied to the endpoint that produced them and must be passed unmodified.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AvatarPresenterListResponse
            List of avatar presenters. Pass an `avatarPresenterId` to `POST /v1/tools/generate-avatar`.

        Examples
        --------
        import asyncio

        from videogen import AsyncVideoGenApi

        client = AsyncVideoGenApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.resources.list_avatar_presenters()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_avatar_presenters(
            limit=limit, cursor=cursor, request_options=request_options
        )
        return _response.data

    async def list_tts_voices(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        include_deprecated_voices: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TtsVoiceListResponse:
        """
        List available text-to-speech voices. Pass a `voiceId` from the response to the text-to-speech endpoint. Paginated; pass `nextCursor` from the previous response as `cursor` to fetch the next page.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum number of items to return in the page. Defaults to 50; capped at 200.

        cursor : typing.Optional[str]
            Opaque pagination cursor returned as `nextCursor` by the previous page. Omit on the first request. Cursors are tied to the endpoint that produced them and must be passed unmodified.

        include_deprecated_voices : typing.Optional[bool]
            When true, includes voices that are deprecated but still callable. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TtsVoiceListResponse
            List of TTS voices. Pass a `voiceId` to `POST /v1/tools/text-to-speech`.

        Examples
        --------
        import asyncio

        from videogen import AsyncVideoGenApi

        client = AsyncVideoGenApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.resources.list_tts_voices()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_tts_voices(
            limit=limit,
            cursor=cursor,
            include_deprecated_voices=include_deprecated_voices,
            request_options=request_options,
        )
        return _response.data
