# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.entity import Entity
from ..types.entity_archive_response import EntityArchiveResponse
from ..types.list_entities_response import ListEntitiesResponse
from .raw_client import AsyncRawEntitiesClient, RawEntitiesClient
from .types.create_entity_request_entity_type import CreateEntityRequestEntityType
from .types.list_entities_request_entity_type import ListEntitiesRequestEntityType

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class EntitiesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEntitiesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEntitiesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEntitiesClient
        """
        return self._raw_client

    def list_entities(
        self,
        *,
        entity_type: typing.Optional[ListEntitiesRequestEntityType] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListEntitiesResponse:
        """
        List the actors and visual styles available to your team, most recently updated first. Cursor-paginated; see the [Pagination](/pagination) guide.

        Parameters
        ----------
        entity_type : typing.Optional[ListEntitiesRequestEntityType]
            When provided, returns only entities of this type. Omit to return all entities.

        limit : typing.Optional[int]
            Maximum number of items to return in the page. Defaults to 50; capped at 200. See [Pagination](/pagination).

        cursor : typing.Optional[str]
            Opaque pagination cursor returned as `nextCursor` by the previous page. Omit on the first request. Cursors are tied to the endpoint that produced them and must be passed unmodified. See [Pagination](/pagination).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListEntitiesResponse
            Entity list

        Examples
        --------
        from videogen import VideoGenApi

        client = VideoGenApi(
            token="YOUR_TOKEN",
        )
        client.entities.list_entities()
        """
        _response = self._raw_client.list_entities(
            entity_type=entity_type, limit=limit, cursor=cursor, request_options=request_options
        )
        return _response.data

    def create_entity(
        self,
        *,
        entity_type: CreateEntityRequestEntityType,
        name: str,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Entity:
        """
        Create a new actor or visual style. Attach reference images with `POST /v1/entities/{entityId}/references`.

        Parameters
        ----------
        entity_type : CreateEntityRequestEntityType
            ACTOR features a consistent character; VISUAL_STYLE guides the look of generated images.

        name : str
            Display name.

        description : typing.Optional[str]
            Optional description.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Entity
            The created entity

        Examples
        --------
        from videogen import VideoGenApi

        client = VideoGenApi(
            token="YOUR_TOKEN",
        )
        client.entities.create_entity(
            entity_type="ACTOR",
            name="name",
        )
        """
        _response = self._raw_client.create_entity(
            entity_type=entity_type, name=name, description=description, request_options=request_options
        )
        return _response.data

    def get_entity(self, entity_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Entity:
        """
        Retrieve a single entity by its id, including its reference images.

        Parameters
        ----------
        entity_id : str
            The entity id (e.g. `vg_enti_...`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Entity
            Entity

        Examples
        --------
        from videogen import VideoGenApi

        client = VideoGenApi(
            token="YOUR_TOKEN",
        )
        client.entities.get_entity(
            entity_id="entityId",
        )
        """
        _response = self._raw_client.get_entity(entity_id, request_options=request_options)
        return _response.data

    def update_entity(
        self,
        entity_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Entity:
        """
        Update an entity's name or description. Provide at least one field.

        Parameters
        ----------
        entity_id : str
            The entity id (e.g. `vg_enti_...`).

        name : typing.Optional[str]
            New display name. Omit to leave unchanged.

        description : typing.Optional[str]
            New description. Omit to leave unchanged.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Entity
            The updated entity

        Examples
        --------
        from videogen import VideoGenApi

        client = VideoGenApi(
            token="YOUR_TOKEN",
        )
        client.entities.update_entity(
            entity_id="entityId",
        )
        """
        _response = self._raw_client.update_entity(
            entity_id, name=name, description=description, request_options=request_options
        )
        return _response.data

    def archive_entity(
        self, entity_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EntityArchiveResponse:
        """
        Archive an entity. Archived entities no longer appear in `GET /v1/entities` and can't be attached to new workflows.

        Parameters
        ----------
        entity_id : str
            The entity id (e.g. `vg_enti_...`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityArchiveResponse
            Archive acknowledged

        Examples
        --------
        from videogen import VideoGenApi

        client = VideoGenApi(
            token="YOUR_TOKEN",
        )
        client.entities.archive_entity(
            entity_id="entityId",
        )
        """
        _response = self._raw_client.archive_entity(entity_id, request_options=request_options)
        return _response.data

    def add_entity_reference(
        self,
        entity_id: str,
        *,
        file_id: str,
        description: typing.Optional[str] = OMIT,
        is_default: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Entity:
        """
        Attach an image file as a reference for the entity. Upload the image first via `POST /v1/files/upload`. Returns the updated entity.

        Parameters
        ----------
        entity_id : str
            The entity id (e.g. `vg_enti_...`).

        file_id : str
            The file id (e.g. `vg_file_...`) of an image to attach as a reference.

        description : typing.Optional[str]
            Optional description of the reference.

        is_default : typing.Optional[bool]
            When true, make this the entity's primary reference (used for its thumbnail).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Entity
            The updated entity

        Examples
        --------
        from videogen import VideoGenApi

        client = VideoGenApi(
            token="YOUR_TOKEN",
        )
        client.entities.add_entity_reference(
            entity_id="entityId",
            file_id="fileId",
        )
        """
        _response = self._raw_client.add_entity_reference(
            entity_id, file_id=file_id, description=description, is_default=is_default, request_options=request_options
        )
        return _response.data

    def remove_entity_reference(
        self, entity_id: str, *, file_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> Entity:
        """
        Detach a reference image from the entity. Returns the updated entity.

        Parameters
        ----------
        entity_id : str
            The entity id (e.g. `vg_enti_...`).

        file_id : str
            The file id (e.g. `vg_file_...`) of the reference to remove.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Entity
            The updated entity

        Examples
        --------
        from videogen import VideoGenApi

        client = VideoGenApi(
            token="YOUR_TOKEN",
        )
        client.entities.remove_entity_reference(
            entity_id="entityId",
            file_id="fileId",
        )
        """
        _response = self._raw_client.remove_entity_reference(
            entity_id, file_id=file_id, request_options=request_options
        )
        return _response.data


class AsyncEntitiesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEntitiesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEntitiesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEntitiesClient
        """
        return self._raw_client

    async def list_entities(
        self,
        *,
        entity_type: typing.Optional[ListEntitiesRequestEntityType] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListEntitiesResponse:
        """
        List the actors and visual styles available to your team, most recently updated first. Cursor-paginated; see the [Pagination](/pagination) guide.

        Parameters
        ----------
        entity_type : typing.Optional[ListEntitiesRequestEntityType]
            When provided, returns only entities of this type. Omit to return all entities.

        limit : typing.Optional[int]
            Maximum number of items to return in the page. Defaults to 50; capped at 200. See [Pagination](/pagination).

        cursor : typing.Optional[str]
            Opaque pagination cursor returned as `nextCursor` by the previous page. Omit on the first request. Cursors are tied to the endpoint that produced them and must be passed unmodified. See [Pagination](/pagination).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListEntitiesResponse
            Entity list

        Examples
        --------
        import asyncio

        from videogen import AsyncVideoGenApi

        client = AsyncVideoGenApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.entities.list_entities()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_entities(
            entity_type=entity_type, limit=limit, cursor=cursor, request_options=request_options
        )
        return _response.data

    async def create_entity(
        self,
        *,
        entity_type: CreateEntityRequestEntityType,
        name: str,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Entity:
        """
        Create a new actor or visual style. Attach reference images with `POST /v1/entities/{entityId}/references`.

        Parameters
        ----------
        entity_type : CreateEntityRequestEntityType
            ACTOR features a consistent character; VISUAL_STYLE guides the look of generated images.

        name : str
            Display name.

        description : typing.Optional[str]
            Optional description.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Entity
            The created entity

        Examples
        --------
        import asyncio

        from videogen import AsyncVideoGenApi

        client = AsyncVideoGenApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.entities.create_entity(
                entity_type="ACTOR",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_entity(
            entity_type=entity_type, name=name, description=description, request_options=request_options
        )
        return _response.data

    async def get_entity(self, entity_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Entity:
        """
        Retrieve a single entity by its id, including its reference images.

        Parameters
        ----------
        entity_id : str
            The entity id (e.g. `vg_enti_...`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Entity
            Entity

        Examples
        --------
        import asyncio

        from videogen import AsyncVideoGenApi

        client = AsyncVideoGenApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.entities.get_entity(
                entity_id="entityId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_entity(entity_id, request_options=request_options)
        return _response.data

    async def update_entity(
        self,
        entity_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Entity:
        """
        Update an entity's name or description. Provide at least one field.

        Parameters
        ----------
        entity_id : str
            The entity id (e.g. `vg_enti_...`).

        name : typing.Optional[str]
            New display name. Omit to leave unchanged.

        description : typing.Optional[str]
            New description. Omit to leave unchanged.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Entity
            The updated entity

        Examples
        --------
        import asyncio

        from videogen import AsyncVideoGenApi

        client = AsyncVideoGenApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.entities.update_entity(
                entity_id="entityId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_entity(
            entity_id, name=name, description=description, request_options=request_options
        )
        return _response.data

    async def archive_entity(
        self, entity_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EntityArchiveResponse:
        """
        Archive an entity. Archived entities no longer appear in `GET /v1/entities` and can't be attached to new workflows.

        Parameters
        ----------
        entity_id : str
            The entity id (e.g. `vg_enti_...`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityArchiveResponse
            Archive acknowledged

        Examples
        --------
        import asyncio

        from videogen import AsyncVideoGenApi

        client = AsyncVideoGenApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.entities.archive_entity(
                entity_id="entityId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.archive_entity(entity_id, request_options=request_options)
        return _response.data

    async def add_entity_reference(
        self,
        entity_id: str,
        *,
        file_id: str,
        description: typing.Optional[str] = OMIT,
        is_default: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Entity:
        """
        Attach an image file as a reference for the entity. Upload the image first via `POST /v1/files/upload`. Returns the updated entity.

        Parameters
        ----------
        entity_id : str
            The entity id (e.g. `vg_enti_...`).

        file_id : str
            The file id (e.g. `vg_file_...`) of an image to attach as a reference.

        description : typing.Optional[str]
            Optional description of the reference.

        is_default : typing.Optional[bool]
            When true, make this the entity's primary reference (used for its thumbnail).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Entity
            The updated entity

        Examples
        --------
        import asyncio

        from videogen import AsyncVideoGenApi

        client = AsyncVideoGenApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.entities.add_entity_reference(
                entity_id="entityId",
                file_id="fileId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add_entity_reference(
            entity_id, file_id=file_id, description=description, is_default=is_default, request_options=request_options
        )
        return _response.data

    async def remove_entity_reference(
        self, entity_id: str, *, file_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> Entity:
        """
        Detach a reference image from the entity. Returns the updated entity.

        Parameters
        ----------
        entity_id : str
            The entity id (e.g. `vg_enti_...`).

        file_id : str
            The file id (e.g. `vg_file_...`) of the reference to remove.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Entity
            The updated entity

        Examples
        --------
        import asyncio

        from videogen import AsyncVideoGenApi

        client = AsyncVideoGenApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.entities.remove_entity_reference(
                entity_id="entityId",
                file_id="fileId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.remove_entity_reference(
            entity_id, file_id=file_id, request_options=request_options
        )
        return _response.data
