# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..types.aspect_ratio import AspectRatio
from ..types.executed_tool import ExecutedTool
from ..types.pronunciation_replacement import PronunciationReplacement
from ..types.start_tool_execution_response import StartToolExecutionResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawToolsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def prompt_to_image(
        self,
        *,
        prompt: str,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        num_candidates: typing.Optional[int] = OMIT,
        is_output_temporary: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[StartToolExecutionResponse]:
        """
        Generate an image from a text prompt. Optionally specify an aspect ratio and number of candidates.

        Parameters
        ----------
        prompt : str

        aspect_ratio : typing.Optional[AspectRatio]
            Aspect ratio for the generated image. Defaults to 16:9 when omitted.

        num_candidates : typing.Optional[int]
            Number of output candidates to generate. Defaults to 1.

        is_output_temporary : typing.Optional[bool]
            When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartToolExecutionResponse]
            Execution accepted; poll until complete.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/tools/prompt-to-image",
            method="POST",
            json={
                "prompt": prompt,
                "aspectRatio": convert_and_respect_annotation_metadata(
                    object_=aspect_ratio, annotation=AspectRatio, direction="write"
                ),
                "numCandidates": num_candidates,
                "isOutputTemporary": is_output_temporary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def prompt_to_video_clip(
        self,
        *,
        prompt: str,
        generate_audio: typing.Optional[bool] = OMIT,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        num_candidates: typing.Optional[int] = OMIT,
        is_output_temporary: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[StartToolExecutionResponse]:
        """
        Generate a video clip from a text prompt, with optional audio. Optionally specify an aspect ratio and number of candidates.

        Parameters
        ----------
        prompt : str

        generate_audio : typing.Optional[bool]
            Whether to generate audio alongside the video. Defaults to false.

        aspect_ratio : typing.Optional[AspectRatio]
            Aspect ratio for the generated video. Defaults to 16:9 when omitted.

        num_candidates : typing.Optional[int]
            Number of output candidates to generate. Defaults to 1.

        is_output_temporary : typing.Optional[bool]
            When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartToolExecutionResponse]
            Execution accepted; poll until complete.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/tools/prompt-to-video-clip",
            method="POST",
            json={
                "prompt": prompt,
                "generateAudio": generate_audio,
                "aspectRatio": convert_and_respect_annotation_metadata(
                    object_=aspect_ratio, annotation=AspectRatio, direction="write"
                ),
                "numCandidates": num_candidates,
                "isOutputTemporary": is_output_temporary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def image_to_video_clip(
        self,
        *,
        image_storage_file_id: str,
        prompt: typing.Optional[str] = OMIT,
        generate_audio: typing.Optional[bool] = OMIT,
        source_prompt_to_image_prompt: typing.Optional[str] = OMIT,
        num_candidates: typing.Optional[int] = OMIT,
        is_output_temporary: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[StartToolExecutionResponse]:
        """
        Animate a still image into a video clip using a text prompt. Optionally generate audio alongside the video.

        Parameters
        ----------
        image_storage_file_id : str
            File id of the source image (e.g. `vg_file_...`). Upload a file first via `POST /v1/files/upload`, then pass the returned id here.

        prompt : typing.Optional[str]
            Optional text prompt to guide the animation. When omitted the model infers motion from the image.

        generate_audio : typing.Optional[bool]
            Whether to generate audio alongside the video. Defaults to false.

        source_prompt_to_image_prompt : typing.Optional[str]
            Optional prompt used when the source image was generated.

        num_candidates : typing.Optional[int]
            Number of output candidates to generate. Defaults to 1.

        is_output_temporary : typing.Optional[bool]
            When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartToolExecutionResponse]
            Execution accepted; poll until complete.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/tools/image-to-video-clip",
            method="POST",
            json={
                "imageStorageFileId": image_storage_file_id,
                "prompt": prompt,
                "generateAudio": generate_audio,
                "sourcePromptToImagePrompt": source_prompt_to_image_prompt,
                "numCandidates": num_candidates,
                "isOutputTemporary": is_output_temporary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def image_to_image(
        self,
        *,
        image_storage_file_id: str,
        prompt: str,
        num_candidates: typing.Optional[int] = OMIT,
        is_output_temporary: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[StartToolExecutionResponse]:
        """
        Transform an existing image using a text prompt. The prompt describes the desired changes to apply.

        Parameters
        ----------
        image_storage_file_id : str
            File id of the source image (e.g. `vg_file_...`). Upload a file first via `POST /v1/files/upload`, then pass the returned id here.

        prompt : str
            Prompt describing how to transform the input image.

        num_candidates : typing.Optional[int]
            Number of output candidates to generate. Defaults to 1.

        is_output_temporary : typing.Optional[bool]
            When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartToolExecutionResponse]
            Execution accepted; poll until complete.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/tools/image-to-image",
            method="POST",
            json={
                "imageStorageFileId": image_storage_file_id,
                "prompt": prompt,
                "numCandidates": num_candidates,
                "isOutputTemporary": is_output_temporary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def video_to_video_clip(
        self,
        *,
        video_storage_file_id: str,
        prompt: str,
        num_candidates: typing.Optional[int] = OMIT,
        is_output_temporary: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[StartToolExecutionResponse]:
        """
        Restyle an existing video using a text prompt. The prompt describes the visual transformation to apply.

        Parameters
        ----------
        video_storage_file_id : str
            File id of the source video (e.g. `vg_file_...`). Upload a file first via `POST /v1/files/upload`, then pass the returned id here.

        prompt : str
            Prompt describing how to transform the input video.

        num_candidates : typing.Optional[int]
            Number of output candidates to generate. Defaults to 1.

        is_output_temporary : typing.Optional[bool]
            When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartToolExecutionResponse]
            Execution accepted; poll until complete.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/tools/video-to-video-clip",
            method="POST",
            json={
                "videoStorageFileId": video_storage_file_id,
                "prompt": prompt,
                "numCandidates": num_candidates,
                "isOutputTemporary": is_output_temporary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def text_to_speech(
        self,
        *,
        tts_text: str,
        voice_id: typing.Optional[str] = OMIT,
        speech_language_code: typing.Optional[str] = OMIT,
        pronunciation_replacements: typing.Optional[typing.Sequence[PronunciationReplacement]] = OMIT,
        auto_expand_pronunciation_replacements: typing.Optional[bool] = OMIT,
        voice_speed: typing.Optional[float] = OMIT,
        num_candidates: typing.Optional[int] = OMIT,
        is_output_temporary: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[StartToolExecutionResponse]:
        """
        Convert text into a spoken audio file. Only voices with `supportsDirectToolExecution` set to true can be used. Optionally choose a voice, language, speed, and pronunciation overrides.

        Parameters
        ----------
        tts_text : str

        voice_id : typing.Optional[str]
            Voice id from `GET /v1/resources/tts-voices`. A default voice is used when null. Only voices with `supportsDirectToolExecution` set to true are accepted.

        speech_language_code : typing.Optional[str]
            ISO-639-1 language hint for pronunciation (e.g. `en`, `es`, `zh`).

        pronunciation_replacements : typing.Optional[typing.Sequence[PronunciationReplacement]]

        auto_expand_pronunciation_replacements : typing.Optional[bool]
            When true, automatically expands numbers, symbols, acronyms, and other non-word tokens into their spoken forms before synthesis so the voice pronounces them correctly (e.g. `$100` → `one hundred dollars`, `NASA` → `nasa`, `3rd` → `third`). Defaults to false when omitted.

        voice_speed : typing.Optional[float]
            Speech rate multiplier. Defaults to the voice's default speed.

        num_candidates : typing.Optional[int]
            Number of output candidates to generate. Defaults to 1.

        is_output_temporary : typing.Optional[bool]
            When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartToolExecutionResponse]
            Execution accepted; poll until complete.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/tools/text-to-speech",
            method="POST",
            json={
                "ttsText": tts_text,
                "voiceId": voice_id,
                "speechLanguageCode": speech_language_code,
                "pronunciationReplacements": convert_and_respect_annotation_metadata(
                    object_=pronunciation_replacements,
                    annotation=typing.Sequence[PronunciationReplacement],
                    direction="write",
                ),
                "autoExpandPronunciationReplacements": auto_expand_pronunciation_replacements,
                "voiceSpeed": voice_speed,
                "numCandidates": num_candidates,
                "isOutputTemporary": is_output_temporary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def prompt_to_sound_effect(
        self,
        *,
        prompt: str,
        duration_seconds: typing.Optional[float] = OMIT,
        prompt_influence: typing.Optional[float] = OMIT,
        num_candidates: typing.Optional[int] = OMIT,
        is_output_temporary: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[StartToolExecutionResponse]:
        """
        Generate a sound effect from a text description. Optionally control the duration and prompt influence.

        Parameters
        ----------
        prompt : str

        duration_seconds : typing.Optional[float]

        prompt_influence : typing.Optional[float]

        num_candidates : typing.Optional[int]
            Number of output candidates to generate. Defaults to 1.

        is_output_temporary : typing.Optional[bool]
            When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartToolExecutionResponse]
            Execution accepted; poll until complete.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/tools/prompt-to-sound-effect",
            method="POST",
            json={
                "prompt": prompt,
                "durationSeconds": duration_seconds,
                "promptInfluence": prompt_influence,
                "numCandidates": num_candidates,
                "isOutputTemporary": is_output_temporary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def audio_to_avatar_clip(
        self,
        *,
        avatar_presenter_id: str,
        audio_storage_file_id: str,
        num_candidates: typing.Optional[int] = OMIT,
        is_output_temporary: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[StartToolExecutionResponse]:
        """
        Generate a talking-head avatar video by pairing a presenter with an audio file, typically from a prior text-to-speech result.

        Parameters
        ----------
        avatar_presenter_id : str
            Presenter id from `GET /v1/resources/avatar-presenters`.

        audio_storage_file_id : str
            File id of an AUDIO file (e.g. `vg_file_...`), typically from a prior text-to-speech result. Upload a file first via `POST /v1/files/upload` or generate one with `POST /v1/tools/text-to-speech`, then pass the returned id here.

        num_candidates : typing.Optional[int]
            Number of output candidates to generate. Defaults to 1.

        is_output_temporary : typing.Optional[bool]
            When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartToolExecutionResponse]
            Execution accepted; poll until complete.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/tools/audio-to-avatar-clip",
            method="POST",
            json={
                "avatarPresenterId": avatar_presenter_id,
                "audioStorageFileId": audio_storage_file_id,
                "numCandidates": num_candidates,
                "isOutputTemporary": is_output_temporary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def vectorize_image(
        self,
        *,
        image_storage_file_id: str,
        num_candidates: typing.Optional[int] = OMIT,
        is_output_temporary: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[StartToolExecutionResponse]:
        """
        Convert any raster image into a scalable vector graphic (SVG). The output traces the shapes and colors of the input image.

        Parameters
        ----------
        image_storage_file_id : str
            File id of the source image (e.g. `vg_file_...`). Upload a file first via `POST /v1/files/upload`, then pass the returned id here.

        num_candidates : typing.Optional[int]
            Number of output candidates to generate. Defaults to 1.

        is_output_temporary : typing.Optional[bool]
            When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartToolExecutionResponse]
            Execution accepted; poll until complete.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/tools/vectorize-image",
            method="POST",
            json={
                "imageStorageFileId": image_storage_file_id,
                "numCandidates": num_candidates,
                "isOutputTemporary": is_output_temporary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def remove_image_background(
        self,
        *,
        image_storage_file_id: str,
        num_candidates: typing.Optional[int] = OMIT,
        is_output_temporary: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[StartToolExecutionResponse]:
        """
        Remove the background from an image, returning a transparent-background PNG of the foreground subject.

        Parameters
        ----------
        image_storage_file_id : str
            File id of the source image (e.g. `vg_file_...`). Upload a file first via `POST /v1/files/upload`, then pass the returned id here.

        num_candidates : typing.Optional[int]
            Number of output candidates to generate. Defaults to 1.

        is_output_temporary : typing.Optional[bool]
            When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartToolExecutionResponse]
            Execution accepted; poll until complete.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/tools/remove-image-background",
            method="POST",
            json={
                "imageStorageFileId": image_storage_file_id,
                "numCandidates": num_candidates,
                "isOutputTemporary": is_output_temporary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def remove_video_background(
        self,
        *,
        video_storage_file_id: str,
        num_candidates: typing.Optional[int] = OMIT,
        is_output_temporary: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[StartToolExecutionResponse]:
        """
        Remove the background from a video, producing a transparent-background video of the foreground subject.

        Parameters
        ----------
        video_storage_file_id : str
            File id of the source video (e.g. `vg_file_...`). Upload a file first via `POST /v1/files/upload`, then pass the returned id here.

        num_candidates : typing.Optional[int]
            Number of output candidates to generate. Defaults to 1.

        is_output_temporary : typing.Optional[bool]
            When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartToolExecutionResponse]
            Execution accepted; poll until complete.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/tools/remove-video-background",
            method="POST",
            json={
                "videoStorageFileId": video_storage_file_id,
                "numCandidates": num_candidates,
                "isOutputTemporary": is_output_temporary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def upscale_image(
        self,
        *,
        image_storage_file_id: str,
        num_candidates: typing.Optional[int] = OMIT,
        is_output_temporary: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[StartToolExecutionResponse]:
        """
        Increase the resolution of an image while preserving detail and sharpness.

        Parameters
        ----------
        image_storage_file_id : str
            File id of the source image (e.g. `vg_file_...`). Upload a file first via `POST /v1/files/upload`, then pass the returned id here.

        num_candidates : typing.Optional[int]
            Number of output candidates to generate. Defaults to 1.

        is_output_temporary : typing.Optional[bool]
            When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartToolExecutionResponse]
            Execution accepted; poll until complete.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/tools/upscale-image",
            method="POST",
            json={
                "imageStorageFileId": image_storage_file_id,
                "numCandidates": num_candidates,
                "isOutputTemporary": is_output_temporary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def upscale_video(
        self,
        *,
        video_storage_file_id: str,
        num_candidates: typing.Optional[int] = OMIT,
        is_output_temporary: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[StartToolExecutionResponse]:
        """
        Increase the resolution of a video while preserving detail and sharpness.

        Parameters
        ----------
        video_storage_file_id : str
            File id of the source video (e.g. `vg_file_...`). Upload a file first via `POST /v1/files/upload`, then pass the returned id here.

        num_candidates : typing.Optional[int]
            Number of output candidates to generate. Defaults to 1.

        is_output_temporary : typing.Optional[bool]
            When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartToolExecutionResponse]
            Execution accepted; poll until complete.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/tools/upscale-video",
            method="POST",
            json={
                "videoStorageFileId": video_storage_file_id,
                "numCandidates": num_candidates,
                "isOutputTemporary": is_output_temporary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def cancel_tool_execution(
        self, tool_execution_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[StartToolExecutionResponse]:
        """
        Request cancellation of a running tool execution. The execution transitions to `cancelled` if it has not already completed.

        Parameters
        ----------
        tool_execution_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartToolExecutionResponse]
            Cancellation request accepted
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/tools/executions/{encode_path_param(tool_execution_id)}/cancel",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_tool_execution_info(
        self, tool_execution_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ExecutedTool]:
        """
        Retrieve the current status and result of a tool execution. Poll this endpoint until `status` is `succeeded`, `failed`, or `cancelled`.

        Parameters
        ----------
        tool_execution_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ExecutedTool]
            Current execution state
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/tools/executions/{encode_path_param(tool_execution_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ExecutedTool,
                    parse_obj_as(
                        type_=ExecutedTool,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawToolsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def prompt_to_image(
        self,
        *,
        prompt: str,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        num_candidates: typing.Optional[int] = OMIT,
        is_output_temporary: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[StartToolExecutionResponse]:
        """
        Generate an image from a text prompt. Optionally specify an aspect ratio and number of candidates.

        Parameters
        ----------
        prompt : str

        aspect_ratio : typing.Optional[AspectRatio]
            Aspect ratio for the generated image. Defaults to 16:9 when omitted.

        num_candidates : typing.Optional[int]
            Number of output candidates to generate. Defaults to 1.

        is_output_temporary : typing.Optional[bool]
            When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartToolExecutionResponse]
            Execution accepted; poll until complete.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/tools/prompt-to-image",
            method="POST",
            json={
                "prompt": prompt,
                "aspectRatio": convert_and_respect_annotation_metadata(
                    object_=aspect_ratio, annotation=AspectRatio, direction="write"
                ),
                "numCandidates": num_candidates,
                "isOutputTemporary": is_output_temporary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def prompt_to_video_clip(
        self,
        *,
        prompt: str,
        generate_audio: typing.Optional[bool] = OMIT,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        num_candidates: typing.Optional[int] = OMIT,
        is_output_temporary: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[StartToolExecutionResponse]:
        """
        Generate a video clip from a text prompt, with optional audio. Optionally specify an aspect ratio and number of candidates.

        Parameters
        ----------
        prompt : str

        generate_audio : typing.Optional[bool]
            Whether to generate audio alongside the video. Defaults to false.

        aspect_ratio : typing.Optional[AspectRatio]
            Aspect ratio for the generated video. Defaults to 16:9 when omitted.

        num_candidates : typing.Optional[int]
            Number of output candidates to generate. Defaults to 1.

        is_output_temporary : typing.Optional[bool]
            When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartToolExecutionResponse]
            Execution accepted; poll until complete.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/tools/prompt-to-video-clip",
            method="POST",
            json={
                "prompt": prompt,
                "generateAudio": generate_audio,
                "aspectRatio": convert_and_respect_annotation_metadata(
                    object_=aspect_ratio, annotation=AspectRatio, direction="write"
                ),
                "numCandidates": num_candidates,
                "isOutputTemporary": is_output_temporary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def image_to_video_clip(
        self,
        *,
        image_storage_file_id: str,
        prompt: typing.Optional[str] = OMIT,
        generate_audio: typing.Optional[bool] = OMIT,
        source_prompt_to_image_prompt: typing.Optional[str] = OMIT,
        num_candidates: typing.Optional[int] = OMIT,
        is_output_temporary: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[StartToolExecutionResponse]:
        """
        Animate a still image into a video clip using a text prompt. Optionally generate audio alongside the video.

        Parameters
        ----------
        image_storage_file_id : str
            File id of the source image (e.g. `vg_file_...`). Upload a file first via `POST /v1/files/upload`, then pass the returned id here.

        prompt : typing.Optional[str]
            Optional text prompt to guide the animation. When omitted the model infers motion from the image.

        generate_audio : typing.Optional[bool]
            Whether to generate audio alongside the video. Defaults to false.

        source_prompt_to_image_prompt : typing.Optional[str]
            Optional prompt used when the source image was generated.

        num_candidates : typing.Optional[int]
            Number of output candidates to generate. Defaults to 1.

        is_output_temporary : typing.Optional[bool]
            When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartToolExecutionResponse]
            Execution accepted; poll until complete.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/tools/image-to-video-clip",
            method="POST",
            json={
                "imageStorageFileId": image_storage_file_id,
                "prompt": prompt,
                "generateAudio": generate_audio,
                "sourcePromptToImagePrompt": source_prompt_to_image_prompt,
                "numCandidates": num_candidates,
                "isOutputTemporary": is_output_temporary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def image_to_image(
        self,
        *,
        image_storage_file_id: str,
        prompt: str,
        num_candidates: typing.Optional[int] = OMIT,
        is_output_temporary: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[StartToolExecutionResponse]:
        """
        Transform an existing image using a text prompt. The prompt describes the desired changes to apply.

        Parameters
        ----------
        image_storage_file_id : str
            File id of the source image (e.g. `vg_file_...`). Upload a file first via `POST /v1/files/upload`, then pass the returned id here.

        prompt : str
            Prompt describing how to transform the input image.

        num_candidates : typing.Optional[int]
            Number of output candidates to generate. Defaults to 1.

        is_output_temporary : typing.Optional[bool]
            When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartToolExecutionResponse]
            Execution accepted; poll until complete.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/tools/image-to-image",
            method="POST",
            json={
                "imageStorageFileId": image_storage_file_id,
                "prompt": prompt,
                "numCandidates": num_candidates,
                "isOutputTemporary": is_output_temporary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def video_to_video_clip(
        self,
        *,
        video_storage_file_id: str,
        prompt: str,
        num_candidates: typing.Optional[int] = OMIT,
        is_output_temporary: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[StartToolExecutionResponse]:
        """
        Restyle an existing video using a text prompt. The prompt describes the visual transformation to apply.

        Parameters
        ----------
        video_storage_file_id : str
            File id of the source video (e.g. `vg_file_...`). Upload a file first via `POST /v1/files/upload`, then pass the returned id here.

        prompt : str
            Prompt describing how to transform the input video.

        num_candidates : typing.Optional[int]
            Number of output candidates to generate. Defaults to 1.

        is_output_temporary : typing.Optional[bool]
            When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartToolExecutionResponse]
            Execution accepted; poll until complete.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/tools/video-to-video-clip",
            method="POST",
            json={
                "videoStorageFileId": video_storage_file_id,
                "prompt": prompt,
                "numCandidates": num_candidates,
                "isOutputTemporary": is_output_temporary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def text_to_speech(
        self,
        *,
        tts_text: str,
        voice_id: typing.Optional[str] = OMIT,
        speech_language_code: typing.Optional[str] = OMIT,
        pronunciation_replacements: typing.Optional[typing.Sequence[PronunciationReplacement]] = OMIT,
        auto_expand_pronunciation_replacements: typing.Optional[bool] = OMIT,
        voice_speed: typing.Optional[float] = OMIT,
        num_candidates: typing.Optional[int] = OMIT,
        is_output_temporary: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[StartToolExecutionResponse]:
        """
        Convert text into a spoken audio file. Only voices with `supportsDirectToolExecution` set to true can be used. Optionally choose a voice, language, speed, and pronunciation overrides.

        Parameters
        ----------
        tts_text : str

        voice_id : typing.Optional[str]
            Voice id from `GET /v1/resources/tts-voices`. A default voice is used when null. Only voices with `supportsDirectToolExecution` set to true are accepted.

        speech_language_code : typing.Optional[str]
            ISO-639-1 language hint for pronunciation (e.g. `en`, `es`, `zh`).

        pronunciation_replacements : typing.Optional[typing.Sequence[PronunciationReplacement]]

        auto_expand_pronunciation_replacements : typing.Optional[bool]
            When true, automatically expands numbers, symbols, acronyms, and other non-word tokens into their spoken forms before synthesis so the voice pronounces them correctly (e.g. `$100` → `one hundred dollars`, `NASA` → `nasa`, `3rd` → `third`). Defaults to false when omitted.

        voice_speed : typing.Optional[float]
            Speech rate multiplier. Defaults to the voice's default speed.

        num_candidates : typing.Optional[int]
            Number of output candidates to generate. Defaults to 1.

        is_output_temporary : typing.Optional[bool]
            When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartToolExecutionResponse]
            Execution accepted; poll until complete.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/tools/text-to-speech",
            method="POST",
            json={
                "ttsText": tts_text,
                "voiceId": voice_id,
                "speechLanguageCode": speech_language_code,
                "pronunciationReplacements": convert_and_respect_annotation_metadata(
                    object_=pronunciation_replacements,
                    annotation=typing.Sequence[PronunciationReplacement],
                    direction="write",
                ),
                "autoExpandPronunciationReplacements": auto_expand_pronunciation_replacements,
                "voiceSpeed": voice_speed,
                "numCandidates": num_candidates,
                "isOutputTemporary": is_output_temporary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def prompt_to_sound_effect(
        self,
        *,
        prompt: str,
        duration_seconds: typing.Optional[float] = OMIT,
        prompt_influence: typing.Optional[float] = OMIT,
        num_candidates: typing.Optional[int] = OMIT,
        is_output_temporary: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[StartToolExecutionResponse]:
        """
        Generate a sound effect from a text description. Optionally control the duration and prompt influence.

        Parameters
        ----------
        prompt : str

        duration_seconds : typing.Optional[float]

        prompt_influence : typing.Optional[float]

        num_candidates : typing.Optional[int]
            Number of output candidates to generate. Defaults to 1.

        is_output_temporary : typing.Optional[bool]
            When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartToolExecutionResponse]
            Execution accepted; poll until complete.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/tools/prompt-to-sound-effect",
            method="POST",
            json={
                "prompt": prompt,
                "durationSeconds": duration_seconds,
                "promptInfluence": prompt_influence,
                "numCandidates": num_candidates,
                "isOutputTemporary": is_output_temporary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def audio_to_avatar_clip(
        self,
        *,
        avatar_presenter_id: str,
        audio_storage_file_id: str,
        num_candidates: typing.Optional[int] = OMIT,
        is_output_temporary: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[StartToolExecutionResponse]:
        """
        Generate a talking-head avatar video by pairing a presenter with an audio file, typically from a prior text-to-speech result.

        Parameters
        ----------
        avatar_presenter_id : str
            Presenter id from `GET /v1/resources/avatar-presenters`.

        audio_storage_file_id : str
            File id of an AUDIO file (e.g. `vg_file_...`), typically from a prior text-to-speech result. Upload a file first via `POST /v1/files/upload` or generate one with `POST /v1/tools/text-to-speech`, then pass the returned id here.

        num_candidates : typing.Optional[int]
            Number of output candidates to generate. Defaults to 1.

        is_output_temporary : typing.Optional[bool]
            When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartToolExecutionResponse]
            Execution accepted; poll until complete.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/tools/audio-to-avatar-clip",
            method="POST",
            json={
                "avatarPresenterId": avatar_presenter_id,
                "audioStorageFileId": audio_storage_file_id,
                "numCandidates": num_candidates,
                "isOutputTemporary": is_output_temporary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def vectorize_image(
        self,
        *,
        image_storage_file_id: str,
        num_candidates: typing.Optional[int] = OMIT,
        is_output_temporary: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[StartToolExecutionResponse]:
        """
        Convert any raster image into a scalable vector graphic (SVG). The output traces the shapes and colors of the input image.

        Parameters
        ----------
        image_storage_file_id : str
            File id of the source image (e.g. `vg_file_...`). Upload a file first via `POST /v1/files/upload`, then pass the returned id here.

        num_candidates : typing.Optional[int]
            Number of output candidates to generate. Defaults to 1.

        is_output_temporary : typing.Optional[bool]
            When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartToolExecutionResponse]
            Execution accepted; poll until complete.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/tools/vectorize-image",
            method="POST",
            json={
                "imageStorageFileId": image_storage_file_id,
                "numCandidates": num_candidates,
                "isOutputTemporary": is_output_temporary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def remove_image_background(
        self,
        *,
        image_storage_file_id: str,
        num_candidates: typing.Optional[int] = OMIT,
        is_output_temporary: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[StartToolExecutionResponse]:
        """
        Remove the background from an image, returning a transparent-background PNG of the foreground subject.

        Parameters
        ----------
        image_storage_file_id : str
            File id of the source image (e.g. `vg_file_...`). Upload a file first via `POST /v1/files/upload`, then pass the returned id here.

        num_candidates : typing.Optional[int]
            Number of output candidates to generate. Defaults to 1.

        is_output_temporary : typing.Optional[bool]
            When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartToolExecutionResponse]
            Execution accepted; poll until complete.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/tools/remove-image-background",
            method="POST",
            json={
                "imageStorageFileId": image_storage_file_id,
                "numCandidates": num_candidates,
                "isOutputTemporary": is_output_temporary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def remove_video_background(
        self,
        *,
        video_storage_file_id: str,
        num_candidates: typing.Optional[int] = OMIT,
        is_output_temporary: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[StartToolExecutionResponse]:
        """
        Remove the background from a video, producing a transparent-background video of the foreground subject.

        Parameters
        ----------
        video_storage_file_id : str
            File id of the source video (e.g. `vg_file_...`). Upload a file first via `POST /v1/files/upload`, then pass the returned id here.

        num_candidates : typing.Optional[int]
            Number of output candidates to generate. Defaults to 1.

        is_output_temporary : typing.Optional[bool]
            When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartToolExecutionResponse]
            Execution accepted; poll until complete.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/tools/remove-video-background",
            method="POST",
            json={
                "videoStorageFileId": video_storage_file_id,
                "numCandidates": num_candidates,
                "isOutputTemporary": is_output_temporary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def upscale_image(
        self,
        *,
        image_storage_file_id: str,
        num_candidates: typing.Optional[int] = OMIT,
        is_output_temporary: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[StartToolExecutionResponse]:
        """
        Increase the resolution of an image while preserving detail and sharpness.

        Parameters
        ----------
        image_storage_file_id : str
            File id of the source image (e.g. `vg_file_...`). Upload a file first via `POST /v1/files/upload`, then pass the returned id here.

        num_candidates : typing.Optional[int]
            Number of output candidates to generate. Defaults to 1.

        is_output_temporary : typing.Optional[bool]
            When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartToolExecutionResponse]
            Execution accepted; poll until complete.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/tools/upscale-image",
            method="POST",
            json={
                "imageStorageFileId": image_storage_file_id,
                "numCandidates": num_candidates,
                "isOutputTemporary": is_output_temporary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def upscale_video(
        self,
        *,
        video_storage_file_id: str,
        num_candidates: typing.Optional[int] = OMIT,
        is_output_temporary: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[StartToolExecutionResponse]:
        """
        Increase the resolution of a video while preserving detail and sharpness.

        Parameters
        ----------
        video_storage_file_id : str
            File id of the source video (e.g. `vg_file_...`). Upload a file first via `POST /v1/files/upload`, then pass the returned id here.

        num_candidates : typing.Optional[int]
            Number of output candidates to generate. Defaults to 1.

        is_output_temporary : typing.Optional[bool]
            When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartToolExecutionResponse]
            Execution accepted; poll until complete.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/tools/upscale-video",
            method="POST",
            json={
                "videoStorageFileId": video_storage_file_id,
                "numCandidates": num_candidates,
                "isOutputTemporary": is_output_temporary,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def cancel_tool_execution(
        self, tool_execution_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[StartToolExecutionResponse]:
        """
        Request cancellation of a running tool execution. The execution transitions to `cancelled` if it has not already completed.

        Parameters
        ----------
        tool_execution_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartToolExecutionResponse]
            Cancellation request accepted
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/tools/executions/{encode_path_param(tool_execution_id)}/cancel",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartToolExecutionResponse,
                    parse_obj_as(
                        type_=StartToolExecutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_tool_execution_info(
        self, tool_execution_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ExecutedTool]:
        """
        Retrieve the current status and result of a tool execution. Poll this endpoint until `status` is `succeeded`, `failed`, or `cancelled`.

        Parameters
        ----------
        tool_execution_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ExecutedTool]
            Current execution state
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/tools/executions/{encode_path_param(tool_execution_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ExecutedTool,
                    parse_obj_as(
                        type_=ExecutedTool,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
