# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.aspect_ratio import AspectRatio
from ..types.start_workflow_run_response import StartWorkflowRunResponse
from ..types.workflow_run import WorkflowRun
from .raw_client import AsyncRawWorkflowsClient, RawWorkflowsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class WorkflowsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawWorkflowsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawWorkflowsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawWorkflowsClient
        """
        return self._raw_client

    def add_visuals_narrations_and_captions_to_script(
        self,
        *,
        script: str,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> StartWorkflowRunResponse:
        """
        Creates a project and generates a narrated video from a prompt or script. Returns immediately with a workflow run id; poll or subscribe to webhooks for completion.

        Parameters
        ----------
        script : str
            The narration script, used verbatim. This exact text is narrated and turned into a video — it is not rewritten or expanded.

        aspect_ratio : typing.Optional[AspectRatio]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StartWorkflowRunResponse
            Workflow run accepted.

        Examples
        --------
        from videogen import VideoGenApi

        client = VideoGenApi(
            token="YOUR_TOKEN",
        )
        client.workflows.add_visuals_narrations_and_captions_to_script(
            script="script",
        )
        """
        _response = self._raw_client.add_visuals_narrations_and_captions_to_script(
            script=script, aspect_ratio=aspect_ratio, request_options=request_options
        )
        return _response.data

    def add_visuals_and_captions_to_voiceover(
        self,
        *,
        file_id: str,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> StartWorkflowRunResponse:
        """
        Creates a project from an uploaded voiceover file and generates a video with matching b-roll. Upload the voiceover via the files API first.

        Parameters
        ----------
        file_id : str
            Opaque file id of an uploaded voiceover audio file (e.g. `vg_file_...`). Upload the file first via `POST /v1/files/upload`.

        aspect_ratio : typing.Optional[AspectRatio]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StartWorkflowRunResponse
            Workflow run accepted.

        Examples
        --------
        from videogen import VideoGenApi

        client = VideoGenApi(
            token="YOUR_TOKEN",
        )
        client.workflows.add_visuals_and_captions_to_voiceover(
            file_id="fileId",
        )
        """
        _response = self._raw_client.add_visuals_and_captions_to_voiceover(
            file_id=file_id, aspect_ratio=aspect_ratio, request_options=request_options
        )
        return _response.data

    def add_narration_transitions_and_captions_to_slideshow(
        self,
        *,
        file_id: str,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> StartWorkflowRunResponse:
        """
        Creates a project from an uploaded PDF or PowerPoint file and generates an AI-narrated video walking through each slide. Upload the file via `POST /v1/files/upload` first.

        Parameters
        ----------
        file_id : str
            Opaque file id of an uploaded PDF or PowerPoint file (e.g. `vg_file_...`). Upload the file first via `POST /v1/files/upload`.

        aspect_ratio : typing.Optional[AspectRatio]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StartWorkflowRunResponse
            Workflow run accepted.

        Examples
        --------
        from videogen import VideoGenApi

        client = VideoGenApi(
            token="YOUR_TOKEN",
        )
        client.workflows.add_narration_transitions_and_captions_to_slideshow(
            file_id="fileId",
        )
        """
        _response = self._raw_client.add_narration_transitions_and_captions_to_slideshow(
            file_id=file_id, aspect_ratio=aspect_ratio, request_options=request_options
        )
        return _response.data

    def get_workflow_run(
        self, workflow_run_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> WorkflowRun:
        """
        Parameters
        ----------
        workflow_run_id : str
            The workflow run id returned when the workflow was started.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkflowRun
            Current workflow run state.

        Examples
        --------
        from videogen import VideoGenApi

        client = VideoGenApi(
            token="YOUR_TOKEN",
        )
        client.workflows.get_workflow_run(
            workflow_run_id="workflowRunId",
        )
        """
        _response = self._raw_client.get_workflow_run(workflow_run_id, request_options=request_options)
        return _response.data

    def cancel_workflow_run(
        self, workflow_run_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> StartWorkflowRunResponse:
        """
        Parameters
        ----------
        workflow_run_id : str
            The workflow run id returned when the workflow was started.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StartWorkflowRunResponse
            Cancellation request accepted.

        Examples
        --------
        from videogen import VideoGenApi

        client = VideoGenApi(
            token="YOUR_TOKEN",
        )
        client.workflows.cancel_workflow_run(
            workflow_run_id="workflowRunId",
        )
        """
        _response = self._raw_client.cancel_workflow_run(workflow_run_id, request_options=request_options)
        return _response.data


class AsyncWorkflowsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawWorkflowsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawWorkflowsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawWorkflowsClient
        """
        return self._raw_client

    async def add_visuals_narrations_and_captions_to_script(
        self,
        *,
        script: str,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> StartWorkflowRunResponse:
        """
        Creates a project and generates a narrated video from a prompt or script. Returns immediately with a workflow run id; poll or subscribe to webhooks for completion.

        Parameters
        ----------
        script : str
            The narration script, used verbatim. This exact text is narrated and turned into a video — it is not rewritten or expanded.

        aspect_ratio : typing.Optional[AspectRatio]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StartWorkflowRunResponse
            Workflow run accepted.

        Examples
        --------
        import asyncio

        from videogen import AsyncVideoGenApi

        client = AsyncVideoGenApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.workflows.add_visuals_narrations_and_captions_to_script(
                script="script",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add_visuals_narrations_and_captions_to_script(
            script=script, aspect_ratio=aspect_ratio, request_options=request_options
        )
        return _response.data

    async def add_visuals_and_captions_to_voiceover(
        self,
        *,
        file_id: str,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> StartWorkflowRunResponse:
        """
        Creates a project from an uploaded voiceover file and generates a video with matching b-roll. Upload the voiceover via the files API first.

        Parameters
        ----------
        file_id : str
            Opaque file id of an uploaded voiceover audio file (e.g. `vg_file_...`). Upload the file first via `POST /v1/files/upload`.

        aspect_ratio : typing.Optional[AspectRatio]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StartWorkflowRunResponse
            Workflow run accepted.

        Examples
        --------
        import asyncio

        from videogen import AsyncVideoGenApi

        client = AsyncVideoGenApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.workflows.add_visuals_and_captions_to_voiceover(
                file_id="fileId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add_visuals_and_captions_to_voiceover(
            file_id=file_id, aspect_ratio=aspect_ratio, request_options=request_options
        )
        return _response.data

    async def add_narration_transitions_and_captions_to_slideshow(
        self,
        *,
        file_id: str,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> StartWorkflowRunResponse:
        """
        Creates a project from an uploaded PDF or PowerPoint file and generates an AI-narrated video walking through each slide. Upload the file via `POST /v1/files/upload` first.

        Parameters
        ----------
        file_id : str
            Opaque file id of an uploaded PDF or PowerPoint file (e.g. `vg_file_...`). Upload the file first via `POST /v1/files/upload`.

        aspect_ratio : typing.Optional[AspectRatio]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StartWorkflowRunResponse
            Workflow run accepted.

        Examples
        --------
        import asyncio

        from videogen import AsyncVideoGenApi

        client = AsyncVideoGenApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.workflows.add_narration_transitions_and_captions_to_slideshow(
                file_id="fileId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add_narration_transitions_and_captions_to_slideshow(
            file_id=file_id, aspect_ratio=aspect_ratio, request_options=request_options
        )
        return _response.data

    async def get_workflow_run(
        self, workflow_run_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> WorkflowRun:
        """
        Parameters
        ----------
        workflow_run_id : str
            The workflow run id returned when the workflow was started.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkflowRun
            Current workflow run state.

        Examples
        --------
        import asyncio

        from videogen import AsyncVideoGenApi

        client = AsyncVideoGenApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.workflows.get_workflow_run(
                workflow_run_id="workflowRunId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_workflow_run(workflow_run_id, request_options=request_options)
        return _response.data

    async def cancel_workflow_run(
        self, workflow_run_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> StartWorkflowRunResponse:
        """
        Parameters
        ----------
        workflow_run_id : str
            The workflow run id returned when the workflow was started.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StartWorkflowRunResponse
            Cancellation request accepted.

        Examples
        --------
        import asyncio

        from videogen import AsyncVideoGenApi

        client = AsyncVideoGenApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.workflows.cancel_workflow_run(
                workflow_run_id="workflowRunId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel_workflow_run(workflow_run_id, request_options=request_options)
        return _response.data
