# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..types.aspect_ratio import AspectRatio
from ..types.start_workflow_run_response import StartWorkflowRunResponse
from ..types.workflow_run import WorkflowRun
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawWorkflowsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def add_visuals_narrations_and_captions_to_script(
        self,
        *,
        script: str,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[StartWorkflowRunResponse]:
        """
        Creates a project and generates a narrated video from a prompt or script. Returns immediately with a workflow run id; poll or subscribe to webhooks for completion.

        Parameters
        ----------
        script : str
            The narration script, used verbatim. This exact text is narrated and turned into a video — it is not rewritten or expanded.

        aspect_ratio : typing.Optional[AspectRatio]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartWorkflowRunResponse]
            Workflow run accepted.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/workflows/add-visuals-narrations-and-captions-to-script",
            method="POST",
            json={
                "script": script,
                "aspectRatio": convert_and_respect_annotation_metadata(
                    object_=aspect_ratio, annotation=AspectRatio, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartWorkflowRunResponse,
                    parse_obj_as(
                        type_=StartWorkflowRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def add_visuals_and_captions_to_voiceover(
        self,
        *,
        file_id: str,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[StartWorkflowRunResponse]:
        """
        Creates a project from an uploaded voiceover file and generates a video with matching b-roll. Upload the voiceover via the files API first.

        Parameters
        ----------
        file_id : str
            Opaque file id of an uploaded voiceover audio file (e.g. `vg_file_...`). Upload the file first via `POST /v1/files/upload`.

        aspect_ratio : typing.Optional[AspectRatio]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartWorkflowRunResponse]
            Workflow run accepted.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/workflows/add-visuals-and-captions-to-voiceover",
            method="POST",
            json={
                "fileId": file_id,
                "aspectRatio": convert_and_respect_annotation_metadata(
                    object_=aspect_ratio, annotation=AspectRatio, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartWorkflowRunResponse,
                    parse_obj_as(
                        type_=StartWorkflowRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def add_narration_transitions_and_captions_to_slideshow(
        self,
        *,
        file_id: str,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[StartWorkflowRunResponse]:
        """
        Creates a project from an uploaded PDF or PowerPoint file and generates an AI-narrated video walking through each slide. Upload the file via `POST /v1/files/upload` first.

        Parameters
        ----------
        file_id : str
            Opaque file id of an uploaded PDF or PowerPoint file (e.g. `vg_file_...`). Upload the file first via `POST /v1/files/upload`.

        aspect_ratio : typing.Optional[AspectRatio]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartWorkflowRunResponse]
            Workflow run accepted.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/workflows/add-narration-transitions-and-captions-to-slideshow",
            method="POST",
            json={
                "fileId": file_id,
                "aspectRatio": convert_and_respect_annotation_metadata(
                    object_=aspect_ratio, annotation=AspectRatio, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartWorkflowRunResponse,
                    parse_obj_as(
                        type_=StartWorkflowRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_workflow_run(
        self, workflow_run_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[WorkflowRun]:
        """
        Parameters
        ----------
        workflow_run_id : str
            The workflow run id returned when the workflow was started.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WorkflowRun]
            Current workflow run state.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/workflows/runs/{encode_path_param(workflow_run_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowRun,
                    parse_obj_as(
                        type_=WorkflowRun,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def cancel_workflow_run(
        self, workflow_run_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[StartWorkflowRunResponse]:
        """
        Parameters
        ----------
        workflow_run_id : str
            The workflow run id returned when the workflow was started.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartWorkflowRunResponse]
            Cancellation request accepted.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/workflows/runs/{encode_path_param(workflow_run_id)}/cancel",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartWorkflowRunResponse,
                    parse_obj_as(
                        type_=StartWorkflowRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawWorkflowsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def add_visuals_narrations_and_captions_to_script(
        self,
        *,
        script: str,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[StartWorkflowRunResponse]:
        """
        Creates a project and generates a narrated video from a prompt or script. Returns immediately with a workflow run id; poll or subscribe to webhooks for completion.

        Parameters
        ----------
        script : str
            The narration script, used verbatim. This exact text is narrated and turned into a video — it is not rewritten or expanded.

        aspect_ratio : typing.Optional[AspectRatio]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartWorkflowRunResponse]
            Workflow run accepted.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/workflows/add-visuals-narrations-and-captions-to-script",
            method="POST",
            json={
                "script": script,
                "aspectRatio": convert_and_respect_annotation_metadata(
                    object_=aspect_ratio, annotation=AspectRatio, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartWorkflowRunResponse,
                    parse_obj_as(
                        type_=StartWorkflowRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def add_visuals_and_captions_to_voiceover(
        self,
        *,
        file_id: str,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[StartWorkflowRunResponse]:
        """
        Creates a project from an uploaded voiceover file and generates a video with matching b-roll. Upload the voiceover via the files API first.

        Parameters
        ----------
        file_id : str
            Opaque file id of an uploaded voiceover audio file (e.g. `vg_file_...`). Upload the file first via `POST /v1/files/upload`.

        aspect_ratio : typing.Optional[AspectRatio]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartWorkflowRunResponse]
            Workflow run accepted.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/workflows/add-visuals-and-captions-to-voiceover",
            method="POST",
            json={
                "fileId": file_id,
                "aspectRatio": convert_and_respect_annotation_metadata(
                    object_=aspect_ratio, annotation=AspectRatio, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartWorkflowRunResponse,
                    parse_obj_as(
                        type_=StartWorkflowRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def add_narration_transitions_and_captions_to_slideshow(
        self,
        *,
        file_id: str,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[StartWorkflowRunResponse]:
        """
        Creates a project from an uploaded PDF or PowerPoint file and generates an AI-narrated video walking through each slide. Upload the file via `POST /v1/files/upload` first.

        Parameters
        ----------
        file_id : str
            Opaque file id of an uploaded PDF or PowerPoint file (e.g. `vg_file_...`). Upload the file first via `POST /v1/files/upload`.

        aspect_ratio : typing.Optional[AspectRatio]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartWorkflowRunResponse]
            Workflow run accepted.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/workflows/add-narration-transitions-and-captions-to-slideshow",
            method="POST",
            json={
                "fileId": file_id,
                "aspectRatio": convert_and_respect_annotation_metadata(
                    object_=aspect_ratio, annotation=AspectRatio, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartWorkflowRunResponse,
                    parse_obj_as(
                        type_=StartWorkflowRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_workflow_run(
        self, workflow_run_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[WorkflowRun]:
        """
        Parameters
        ----------
        workflow_run_id : str
            The workflow run id returned when the workflow was started.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WorkflowRun]
            Current workflow run state.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/workflows/runs/{encode_path_param(workflow_run_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowRun,
                    parse_obj_as(
                        type_=WorkflowRun,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def cancel_workflow_run(
        self, workflow_run_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[StartWorkflowRunResponse]:
        """
        Parameters
        ----------
        workflow_run_id : str
            The workflow run id returned when the workflow was started.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartWorkflowRunResponse]
            Cancellation request accepted.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/workflows/runs/{encode_path_param(workflow_run_id)}/cancel",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartWorkflowRunResponse,
                    parse_obj_as(
                        type_=StartWorkflowRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
