# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..types.aspect_ratio import AspectRatio
from ..types.generate_storyboard_scene import GenerateStoryboardScene
from ..types.remix_action import RemixAction
from ..types.scene_generation import SceneGeneration
from ..types.start_workflow_run_response import StartWorkflowRunResponse
from ..types.storyboard_to_video_request_quality import StoryboardToVideoRequestQuality
from ..types.visual_pacing import VisualPacing
from ..types.workflow_caption_style import WorkflowCaptionStyle
from ..types.workflow_run import WorkflowRun
from ..types.workflow_visual_style import WorkflowVisualStyle
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawWorkflowsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def script_to_video(
        self,
        *,
        script: str,
        visual_style: WorkflowVisualStyle,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        visual_pacing: typing.Optional[VisualPacing] = OMIT,
        language: typing.Optional[str] = OMIT,
        voice_id: typing.Optional[str] = OMIT,
        voice_speed: typing.Optional[float] = OMIT,
        avatar_presenter_id: typing.Optional[str] = OMIT,
        featured_b_roll_file_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        workflow_agent_context: typing.Optional[str] = OMIT,
        remix_actions: typing.Optional[typing.Sequence[RemixAction]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[StartWorkflowRunResponse]:
        """
        Creates a project and generates a narrated video from a prompt or script. Returns immediately with a workflow run id; poll or subscribe to webhooks for completion.

        Parameters
        ----------
        script : str
            The narration script, used verbatim. This exact text is narrated and turned into a video — it is not rewritten or expanded.

        visual_style : WorkflowVisualStyle

        aspect_ratio : typing.Optional[AspectRatio]

        visual_pacing : typing.Optional[VisualPacing]

        language : typing.Optional[str]
            Output language as a BCP-47 code (e.g. `en`, `es`, `fr`). Defaults to English.

        voice_id : typing.Optional[str]
            Voice id from `GET /v1/resources/tts-voices` (e.g. `vg_voic_...`). A default voice is used when omitted. Any voice may be used here, including voices where `supportsDirectToolExecution` is false.

        voice_speed : typing.Optional[float]
            Speech rate multiplier. Defaults to the voice's default speed.

        avatar_presenter_id : typing.Optional[str]
            Optional avatar presenter id from `GET /v1/resources/avatar-presenters` (e.g. `vg_pres_...`). When set, the narration is delivered by a talking-head presenter avatar. Pass your `voiceId` to that endpoint to list presenters sorted by best match for the voice. Omit for a standard voiceover with no presenter.

        featured_b_roll_file_ids : typing.Optional[typing.Sequence[str]]
            Optional file ids of images or videos to feature as b-roll (e.g. `["vg_file_..."]`). Upload files first via `POST /v1/files/upload`. Only image and video files are accepted.

        workflow_agent_context : typing.Optional[str]
            Optional production notes for the AI that builds the video — visual direction that should not appear in the spoken narration (e.g. on-screen code or text to display, specific b-roll to feature, or scene-by-scene staging). Never spoken; keep the narration itself in `script`.

        remix_actions : typing.Optional[typing.Sequence[RemixAction]]
            Optional edits applied to the project after the video is built, in order. Each action runs asynchronously; the response returns one remix action id per action. Recommended for script-to-video: `ENABLE_CAPTIONS` to show and style captions, `SET_BACKGROUND_MUSIC` to add a music bed, `ADD_TRANSITIONS` to stamp transitions between sections, and `SET_LOGO` to overlay a logo (this workflow has no native caption-style or logo fields). `EDIT_WITH_AGENT` applies open-ended natural-language edits. See the [Remix actions](/remix-actions) guide.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartWorkflowRunResponse]
            Workflow run accepted.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/workflows/script-to-video",
            method="POST",
            json={
                "script": script,
                "aspectRatio": convert_and_respect_annotation_metadata(
                    object_=aspect_ratio, annotation=AspectRatio, direction="write"
                ),
                "visualStyle": convert_and_respect_annotation_metadata(
                    object_=visual_style, annotation=WorkflowVisualStyle, direction="write"
                ),
                "visualPacing": visual_pacing,
                "language": language,
                "voiceId": voice_id,
                "voiceSpeed": voice_speed,
                "avatarPresenterId": avatar_presenter_id,
                "featuredBRollFileIds": featured_b_roll_file_ids,
                "workflowAgentContext": workflow_agent_context,
                "remixActions": convert_and_respect_annotation_metadata(
                    object_=remix_actions, annotation=typing.Sequence[RemixAction], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartWorkflowRunResponse,
                    parse_obj_as(
                        type_=StartWorkflowRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def add_visuals_narrations_and_captions_to_script(
        self,
        *,
        script: str,
        visual_style: WorkflowVisualStyle,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        visual_pacing: typing.Optional[VisualPacing] = OMIT,
        language: typing.Optional[str] = OMIT,
        voice_id: typing.Optional[str] = OMIT,
        voice_speed: typing.Optional[float] = OMIT,
        avatar_presenter_id: typing.Optional[str] = OMIT,
        featured_b_roll_file_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        workflow_agent_context: typing.Optional[str] = OMIT,
        remix_actions: typing.Optional[typing.Sequence[RemixAction]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[StartWorkflowRunResponse]:
        """
        Legacy alias for `POST /v1/workflows/script-to-video`. Use that endpoint instead.

        Parameters
        ----------
        script : str
            The narration script, used verbatim. This exact text is narrated and turned into a video — it is not rewritten or expanded.

        visual_style : WorkflowVisualStyle

        aspect_ratio : typing.Optional[AspectRatio]

        visual_pacing : typing.Optional[VisualPacing]

        language : typing.Optional[str]
            Output language as a BCP-47 code (e.g. `en`, `es`, `fr`). Defaults to English.

        voice_id : typing.Optional[str]
            Voice id from `GET /v1/resources/tts-voices` (e.g. `vg_voic_...`). A default voice is used when omitted. Any voice may be used here, including voices where `supportsDirectToolExecution` is false.

        voice_speed : typing.Optional[float]
            Speech rate multiplier. Defaults to the voice's default speed.

        avatar_presenter_id : typing.Optional[str]
            Optional avatar presenter id from `GET /v1/resources/avatar-presenters` (e.g. `vg_pres_...`). When set, the narration is delivered by a talking-head presenter avatar. Pass your `voiceId` to that endpoint to list presenters sorted by best match for the voice. Omit for a standard voiceover with no presenter.

        featured_b_roll_file_ids : typing.Optional[typing.Sequence[str]]
            Optional file ids of images or videos to feature as b-roll (e.g. `["vg_file_..."]`). Upload files first via `POST /v1/files/upload`. Only image and video files are accepted.

        workflow_agent_context : typing.Optional[str]
            Optional production notes for the AI that builds the video — visual direction that should not appear in the spoken narration (e.g. on-screen code or text to display, specific b-roll to feature, or scene-by-scene staging). Never spoken; keep the narration itself in `script`.

        remix_actions : typing.Optional[typing.Sequence[RemixAction]]
            Optional edits applied to the project after the video is built, in order. Each action runs asynchronously; the response returns one remix action id per action. Recommended for script-to-video: `ENABLE_CAPTIONS` to show and style captions, `SET_BACKGROUND_MUSIC` to add a music bed, `ADD_TRANSITIONS` to stamp transitions between sections, and `SET_LOGO` to overlay a logo (this workflow has no native caption-style or logo fields). `EDIT_WITH_AGENT` applies open-ended natural-language edits. See the [Remix actions](/remix-actions) guide.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartWorkflowRunResponse]
            Workflow run accepted.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/workflows/add-visuals-narrations-and-captions-to-script",
            method="POST",
            json={
                "script": script,
                "aspectRatio": convert_and_respect_annotation_metadata(
                    object_=aspect_ratio, annotation=AspectRatio, direction="write"
                ),
                "visualStyle": convert_and_respect_annotation_metadata(
                    object_=visual_style, annotation=WorkflowVisualStyle, direction="write"
                ),
                "visualPacing": visual_pacing,
                "language": language,
                "voiceId": voice_id,
                "voiceSpeed": voice_speed,
                "avatarPresenterId": avatar_presenter_id,
                "featuredBRollFileIds": featured_b_roll_file_ids,
                "workflowAgentContext": workflow_agent_context,
                "remixActions": convert_and_respect_annotation_metadata(
                    object_=remix_actions, annotation=typing.Sequence[RemixAction], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartWorkflowRunResponse,
                    parse_obj_as(
                        type_=StartWorkflowRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def voiceover_to_video(
        self,
        *,
        file_id: str,
        visual_style: WorkflowVisualStyle,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        visual_pacing: typing.Optional[VisualPacing] = OMIT,
        language: typing.Optional[str] = OMIT,
        caption_style: typing.Optional[WorkflowCaptionStyle] = OMIT,
        logo_file_id: typing.Optional[str] = OMIT,
        workflow_agent_context: typing.Optional[str] = OMIT,
        remix_actions: typing.Optional[typing.Sequence[RemixAction]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[StartWorkflowRunResponse]:
        """
        Creates a project from an uploaded voiceover file and generates a video with matching b-roll. Upload the voiceover via the files API first.

        Parameters
        ----------
        file_id : str
            Opaque file id of an uploaded voiceover audio file (e.g. `vg_file_...`). Upload the file first via `POST /v1/files/upload`.

        visual_style : WorkflowVisualStyle

        aspect_ratio : typing.Optional[AspectRatio]

        visual_pacing : typing.Optional[VisualPacing]

        language : typing.Optional[str]
            Output language as a BCP-47 code (e.g. `en`, `es`, `fr`). Defaults to English.

        caption_style : typing.Optional[WorkflowCaptionStyle]
            Caption styling. Omit to use the default style with captions shown. Pass an object to override individual style fields (any omitted field uses the default). Pass `null` to hide captions entirely.

        logo_file_id : typing.Optional[str]
            Optional file id of an uploaded logo image to overlay on the video (e.g. `vg_file_...`). Upload the image first via `POST /v1/files/upload`. Only image files are accepted.

        workflow_agent_context : typing.Optional[str]
            Optional production notes for the AI that builds the video — visual direction for how to illustrate the voiceover (e.g. on-screen code or text to display, specific b-roll to feature, or scene-by-scene staging). Never spoken; does not change the uploaded voiceover audio or its transcript.

        remix_actions : typing.Optional[typing.Sequence[RemixAction]]
            Optional edits applied to the project after the video is built, in order. Each action runs asynchronously; the response returns one remix action id per action. Captions and a logo are set with the `captionStyle` and `logoFileId` request fields above; recommended remix actions here are `SET_BACKGROUND_MUSIC` for a music bed, `ADD_TRANSITIONS` to stamp transitions between sections and assets, and `EDIT_WITH_AGENT` for open-ended natural-language edits. See the [Remix actions](/remix-actions) guide.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartWorkflowRunResponse]
            Workflow run accepted.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/workflows/voiceover-to-video",
            method="POST",
            json={
                "fileId": file_id,
                "aspectRatio": convert_and_respect_annotation_metadata(
                    object_=aspect_ratio, annotation=AspectRatio, direction="write"
                ),
                "visualStyle": convert_and_respect_annotation_metadata(
                    object_=visual_style, annotation=WorkflowVisualStyle, direction="write"
                ),
                "visualPacing": visual_pacing,
                "language": language,
                "captionStyle": convert_and_respect_annotation_metadata(
                    object_=caption_style, annotation=typing.Optional[WorkflowCaptionStyle], direction="write"
                ),
                "logoFileId": logo_file_id,
                "workflowAgentContext": workflow_agent_context,
                "remixActions": convert_and_respect_annotation_metadata(
                    object_=remix_actions, annotation=typing.Sequence[RemixAction], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartWorkflowRunResponse,
                    parse_obj_as(
                        type_=StartWorkflowRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def add_visuals_and_captions_to_voiceover(
        self,
        *,
        file_id: str,
        visual_style: WorkflowVisualStyle,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        visual_pacing: typing.Optional[VisualPacing] = OMIT,
        language: typing.Optional[str] = OMIT,
        caption_style: typing.Optional[WorkflowCaptionStyle] = OMIT,
        logo_file_id: typing.Optional[str] = OMIT,
        workflow_agent_context: typing.Optional[str] = OMIT,
        remix_actions: typing.Optional[typing.Sequence[RemixAction]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[StartWorkflowRunResponse]:
        """
        Legacy alias for `POST /v1/workflows/voiceover-to-video`. Use that endpoint instead.

        Parameters
        ----------
        file_id : str
            Opaque file id of an uploaded voiceover audio file (e.g. `vg_file_...`). Upload the file first via `POST /v1/files/upload`.

        visual_style : WorkflowVisualStyle

        aspect_ratio : typing.Optional[AspectRatio]

        visual_pacing : typing.Optional[VisualPacing]

        language : typing.Optional[str]
            Output language as a BCP-47 code (e.g. `en`, `es`, `fr`). Defaults to English.

        caption_style : typing.Optional[WorkflowCaptionStyle]
            Caption styling. Omit to use the default style with captions shown. Pass an object to override individual style fields (any omitted field uses the default). Pass `null` to hide captions entirely.

        logo_file_id : typing.Optional[str]
            Optional file id of an uploaded logo image to overlay on the video (e.g. `vg_file_...`). Upload the image first via `POST /v1/files/upload`. Only image files are accepted.

        workflow_agent_context : typing.Optional[str]
            Optional production notes for the AI that builds the video — visual direction for how to illustrate the voiceover (e.g. on-screen code or text to display, specific b-roll to feature, or scene-by-scene staging). Never spoken; does not change the uploaded voiceover audio or its transcript.

        remix_actions : typing.Optional[typing.Sequence[RemixAction]]
            Optional edits applied to the project after the video is built, in order. Each action runs asynchronously; the response returns one remix action id per action. Captions and a logo are set with the `captionStyle` and `logoFileId` request fields above; recommended remix actions here are `SET_BACKGROUND_MUSIC` for a music bed, `ADD_TRANSITIONS` to stamp transitions between sections and assets, and `EDIT_WITH_AGENT` for open-ended natural-language edits. See the [Remix actions](/remix-actions) guide.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartWorkflowRunResponse]
            Workflow run accepted.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/workflows/add-visuals-and-captions-to-voiceover",
            method="POST",
            json={
                "fileId": file_id,
                "aspectRatio": convert_and_respect_annotation_metadata(
                    object_=aspect_ratio, annotation=AspectRatio, direction="write"
                ),
                "visualStyle": convert_and_respect_annotation_metadata(
                    object_=visual_style, annotation=WorkflowVisualStyle, direction="write"
                ),
                "visualPacing": visual_pacing,
                "language": language,
                "captionStyle": convert_and_respect_annotation_metadata(
                    object_=caption_style, annotation=typing.Optional[WorkflowCaptionStyle], direction="write"
                ),
                "logoFileId": logo_file_id,
                "workflowAgentContext": workflow_agent_context,
                "remixActions": convert_and_respect_annotation_metadata(
                    object_=remix_actions, annotation=typing.Sequence[RemixAction], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartWorkflowRunResponse,
                    parse_obj_as(
                        type_=StartWorkflowRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def slideshow_to_video(
        self,
        *,
        file_id: str,
        slide_scripts: typing.Optional[typing.Sequence[str]] = OMIT,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        language: typing.Optional[str] = OMIT,
        voice_id: typing.Optional[str] = OMIT,
        voice_speed: typing.Optional[float] = OMIT,
        avatar_presenter_id: typing.Optional[str] = OMIT,
        caption_style: typing.Optional[WorkflowCaptionStyle] = OMIT,
        logo_file_id: typing.Optional[str] = OMIT,
        remix_actions: typing.Optional[typing.Sequence[RemixAction]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[StartWorkflowRunResponse]:
        """
        Creates a project from an uploaded PDF or PowerPoint file and generates an AI-narrated video walking through each slide. Upload the file via `POST /v1/files/upload` first.

        Parameters
        ----------
        file_id : str
            Opaque file id of an uploaded PDF or PowerPoint file (e.g. `vg_file_...`). Upload the file first via `POST /v1/files/upload`.

        slide_scripts : typing.Optional[typing.Sequence[str]]
            Optional per-slide narration, in slide order, applied by index: each slide uses its matching entry, and an empty string makes that slide silent. If you provide fewer entries than slides, the remaining slides are silent; extra entries are ignored. Omit this field entirely to narrate each slide from its speaker notes in the uploaded file. To guarantee no narration on any slide, pass an empty array.

        aspect_ratio : typing.Optional[AspectRatio]

        language : typing.Optional[str]
            Output language as a BCP-47 code (e.g. `en`, `es`, `fr`). Defaults to English.

        voice_id : typing.Optional[str]
            Voice id from `GET /v1/resources/tts-voices` (e.g. `vg_voic_...`). A default voice is used when omitted. Any voice may be used here, including voices where `supportsDirectToolExecution` is false.

        voice_speed : typing.Optional[float]
            Speech rate multiplier. Defaults to the voice's default speed.

        avatar_presenter_id : typing.Optional[str]
            Optional avatar presenter id from `GET /v1/resources/avatar-presenters` (e.g. `vg_pres_...`). When set, the narration is delivered by a talking-head presenter avatar. Pass your `voiceId` to that endpoint to list presenters sorted by best match for the voice. Omit for a standard voiceover with no presenter.

        caption_style : typing.Optional[WorkflowCaptionStyle]
            Caption styling. Omit to use the default style with captions shown. Pass an object to override individual style fields (any omitted field uses the default). Pass `null` to hide captions entirely.

        logo_file_id : typing.Optional[str]
            Optional file id of an uploaded logo image to overlay on the video (e.g. `vg_file_...`). Upload the image first via `POST /v1/files/upload`. Only image files are accepted.

        remix_actions : typing.Optional[typing.Sequence[RemixAction]]
            Optional edits applied to the project after the video is built, in order. Each action runs asynchronously; the response returns one remix action id per action. Captions and a logo are set with the `captionStyle` and `logoFileId` request fields above; recommended remix actions here are `SET_BACKGROUND_MUSIC` for a music bed, `ADD_TRANSITIONS` to stamp transitions between sections and assets, and `EDIT_WITH_AGENT` for open-ended natural-language edits. See the [Remix actions](/remix-actions) guide.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartWorkflowRunResponse]
            Workflow run accepted.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/workflows/slideshow-to-video",
            method="POST",
            json={
                "fileId": file_id,
                "slideScripts": slide_scripts,
                "aspectRatio": convert_and_respect_annotation_metadata(
                    object_=aspect_ratio, annotation=AspectRatio, direction="write"
                ),
                "language": language,
                "voiceId": voice_id,
                "voiceSpeed": voice_speed,
                "avatarPresenterId": avatar_presenter_id,
                "captionStyle": convert_and_respect_annotation_metadata(
                    object_=caption_style, annotation=typing.Optional[WorkflowCaptionStyle], direction="write"
                ),
                "logoFileId": logo_file_id,
                "remixActions": convert_and_respect_annotation_metadata(
                    object_=remix_actions, annotation=typing.Sequence[RemixAction], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartWorkflowRunResponse,
                    parse_obj_as(
                        type_=StartWorkflowRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def add_narration_transitions_and_captions_to_slideshow(
        self,
        *,
        file_id: str,
        slide_scripts: typing.Optional[typing.Sequence[str]] = OMIT,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        language: typing.Optional[str] = OMIT,
        voice_id: typing.Optional[str] = OMIT,
        voice_speed: typing.Optional[float] = OMIT,
        avatar_presenter_id: typing.Optional[str] = OMIT,
        caption_style: typing.Optional[WorkflowCaptionStyle] = OMIT,
        logo_file_id: typing.Optional[str] = OMIT,
        remix_actions: typing.Optional[typing.Sequence[RemixAction]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[StartWorkflowRunResponse]:
        """
        Legacy alias for `POST /v1/workflows/slideshow-to-video`. Use that endpoint instead.

        Parameters
        ----------
        file_id : str
            Opaque file id of an uploaded PDF or PowerPoint file (e.g. `vg_file_...`). Upload the file first via `POST /v1/files/upload`.

        slide_scripts : typing.Optional[typing.Sequence[str]]
            Optional per-slide narration, in slide order, applied by index: each slide uses its matching entry, and an empty string makes that slide silent. If you provide fewer entries than slides, the remaining slides are silent; extra entries are ignored. Omit this field entirely to narrate each slide from its speaker notes in the uploaded file. To guarantee no narration on any slide, pass an empty array.

        aspect_ratio : typing.Optional[AspectRatio]

        language : typing.Optional[str]
            Output language as a BCP-47 code (e.g. `en`, `es`, `fr`). Defaults to English.

        voice_id : typing.Optional[str]
            Voice id from `GET /v1/resources/tts-voices` (e.g. `vg_voic_...`). A default voice is used when omitted. Any voice may be used here, including voices where `supportsDirectToolExecution` is false.

        voice_speed : typing.Optional[float]
            Speech rate multiplier. Defaults to the voice's default speed.

        avatar_presenter_id : typing.Optional[str]
            Optional avatar presenter id from `GET /v1/resources/avatar-presenters` (e.g. `vg_pres_...`). When set, the narration is delivered by a talking-head presenter avatar. Pass your `voiceId` to that endpoint to list presenters sorted by best match for the voice. Omit for a standard voiceover with no presenter.

        caption_style : typing.Optional[WorkflowCaptionStyle]
            Caption styling. Omit to use the default style with captions shown. Pass an object to override individual style fields (any omitted field uses the default). Pass `null` to hide captions entirely.

        logo_file_id : typing.Optional[str]
            Optional file id of an uploaded logo image to overlay on the video (e.g. `vg_file_...`). Upload the image first via `POST /v1/files/upload`. Only image files are accepted.

        remix_actions : typing.Optional[typing.Sequence[RemixAction]]
            Optional edits applied to the project after the video is built, in order. Each action runs asynchronously; the response returns one remix action id per action. Captions and a logo are set with the `captionStyle` and `logoFileId` request fields above; recommended remix actions here are `SET_BACKGROUND_MUSIC` for a music bed, `ADD_TRANSITIONS` to stamp transitions between sections and assets, and `EDIT_WITH_AGENT` for open-ended natural-language edits. See the [Remix actions](/remix-actions) guide.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartWorkflowRunResponse]
            Workflow run accepted.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/workflows/add-narration-transitions-and-captions-to-slideshow",
            method="POST",
            json={
                "fileId": file_id,
                "slideScripts": slide_scripts,
                "aspectRatio": convert_and_respect_annotation_metadata(
                    object_=aspect_ratio, annotation=AspectRatio, direction="write"
                ),
                "language": language,
                "voiceId": voice_id,
                "voiceSpeed": voice_speed,
                "avatarPresenterId": avatar_presenter_id,
                "captionStyle": convert_and_respect_annotation_metadata(
                    object_=caption_style, annotation=typing.Optional[WorkflowCaptionStyle], direction="write"
                ),
                "logoFileId": logo_file_id,
                "remixActions": convert_and_respect_annotation_metadata(
                    object_=remix_actions, annotation=typing.Sequence[RemixAction], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartWorkflowRunResponse,
                    parse_obj_as(
                        type_=StartWorkflowRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def storyboard_to_video(
        self,
        *,
        scenes: typing.Sequence[GenerateStoryboardScene],
        default_generation: typing.Optional[SceneGeneration] = OMIT,
        default_duration_seconds: typing.Optional[int] = OMIT,
        quality: typing.Optional[StoryboardToVideoRequestQuality] = OMIT,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        workflow_agent_context: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[StartWorkflowRunResponse]:
        """
        Creates a project from an ordered list of scenes and generates one section per scene. Each scene is generated from its prompt as either a still image or a video clip; the scenes are then assembled into a single video. Returns immediately with a workflow run id; poll or subscribe to webhooks for completion.

        Parameters
        ----------
        scenes : typing.Sequence[GenerateStoryboardScene]
            Ordered list of scenes. Each scene becomes one section in the final video, in this order.

        default_generation : typing.Optional[SceneGeneration]
            Default generation applied to scenes that don't set their own `generation`. Defaults to AI_IMAGE with no extra style.

        default_duration_seconds : typing.Optional[int]
            Default per-scene duration in seconds for scenes that don't set their own `durationSeconds`. Defaults to 5. For AI_VIDEO scenes this must be a whole number between 1 and 15.

        quality : typing.Optional[StoryboardToVideoRequestQuality]
            Generation quality tier for every scene. LOW is fastest and cheapest; STANDARD balances quality and cost; HIGH is highest quality. Defaults to STANDARD. LOW is not supported for AI_VIDEO scenes: the request is rejected if any scene is generated as a video at LOW quality.

        aspect_ratio : typing.Optional[AspectRatio]

        workflow_agent_context : typing.Optional[str]
            Optional storyboard-wide production notes for the AI that builds the video (e.g. recurring characters or props, a consistent setting, or overall staging guidance). Applies across every scene; per-scene direction goes in each scene's `prompt`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartWorkflowRunResponse]
            Workflow run accepted.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/workflows/storyboard-to-video",
            method="POST",
            json={
                "scenes": convert_and_respect_annotation_metadata(
                    object_=scenes, annotation=typing.Sequence[GenerateStoryboardScene], direction="write"
                ),
                "defaultGeneration": convert_and_respect_annotation_metadata(
                    object_=default_generation, annotation=typing.Optional[SceneGeneration], direction="write"
                ),
                "defaultDurationSeconds": default_duration_seconds,
                "quality": quality,
                "aspectRatio": convert_and_respect_annotation_metadata(
                    object_=aspect_ratio, annotation=AspectRatio, direction="write"
                ),
                "workflowAgentContext": workflow_agent_context,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartWorkflowRunResponse,
                    parse_obj_as(
                        type_=StartWorkflowRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def generate_scenes_from_storyboard(
        self,
        *,
        scenes: typing.Sequence[GenerateStoryboardScene],
        default_generation: typing.Optional[SceneGeneration] = OMIT,
        default_duration_seconds: typing.Optional[int] = OMIT,
        quality: typing.Optional[StoryboardToVideoRequestQuality] = OMIT,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        workflow_agent_context: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[StartWorkflowRunResponse]:
        """
        Legacy alias for `POST /v1/workflows/storyboard-to-video`. Use that endpoint instead.

        Parameters
        ----------
        scenes : typing.Sequence[GenerateStoryboardScene]
            Ordered list of scenes. Each scene becomes one section in the final video, in this order.

        default_generation : typing.Optional[SceneGeneration]
            Default generation applied to scenes that don't set their own `generation`. Defaults to AI_IMAGE with no extra style.

        default_duration_seconds : typing.Optional[int]
            Default per-scene duration in seconds for scenes that don't set their own `durationSeconds`. Defaults to 5. For AI_VIDEO scenes this must be a whole number between 1 and 15.

        quality : typing.Optional[StoryboardToVideoRequestQuality]
            Generation quality tier for every scene. LOW is fastest and cheapest; STANDARD balances quality and cost; HIGH is highest quality. Defaults to STANDARD. LOW is not supported for AI_VIDEO scenes: the request is rejected if any scene is generated as a video at LOW quality.

        aspect_ratio : typing.Optional[AspectRatio]

        workflow_agent_context : typing.Optional[str]
            Optional storyboard-wide production notes for the AI that builds the video (e.g. recurring characters or props, a consistent setting, or overall staging guidance). Applies across every scene; per-scene direction goes in each scene's `prompt`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartWorkflowRunResponse]
            Workflow run accepted.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/workflows/generate-scenes-from-storyboard",
            method="POST",
            json={
                "scenes": convert_and_respect_annotation_metadata(
                    object_=scenes, annotation=typing.Sequence[GenerateStoryboardScene], direction="write"
                ),
                "defaultGeneration": convert_and_respect_annotation_metadata(
                    object_=default_generation, annotation=typing.Optional[SceneGeneration], direction="write"
                ),
                "defaultDurationSeconds": default_duration_seconds,
                "quality": quality,
                "aspectRatio": convert_and_respect_annotation_metadata(
                    object_=aspect_ratio, annotation=AspectRatio, direction="write"
                ),
                "workflowAgentContext": workflow_agent_context,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartWorkflowRunResponse,
                    parse_obj_as(
                        type_=StartWorkflowRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_workflow_run(
        self, workflow_run_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[WorkflowRun]:
        """
        Parameters
        ----------
        workflow_run_id : str
            The workflow run id returned when the workflow was started.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WorkflowRun]
            Current workflow run state.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/workflows/runs/{encode_path_param(workflow_run_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowRun,
                    parse_obj_as(
                        type_=WorkflowRun,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def cancel_workflow_run(
        self, workflow_run_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[StartWorkflowRunResponse]:
        """
        Parameters
        ----------
        workflow_run_id : str
            The workflow run id returned when the workflow was started.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StartWorkflowRunResponse]
            Cancellation request accepted.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/workflows/runs/{encode_path_param(workflow_run_id)}/cancel",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartWorkflowRunResponse,
                    parse_obj_as(
                        type_=StartWorkflowRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawWorkflowsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def script_to_video(
        self,
        *,
        script: str,
        visual_style: WorkflowVisualStyle,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        visual_pacing: typing.Optional[VisualPacing] = OMIT,
        language: typing.Optional[str] = OMIT,
        voice_id: typing.Optional[str] = OMIT,
        voice_speed: typing.Optional[float] = OMIT,
        avatar_presenter_id: typing.Optional[str] = OMIT,
        featured_b_roll_file_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        workflow_agent_context: typing.Optional[str] = OMIT,
        remix_actions: typing.Optional[typing.Sequence[RemixAction]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[StartWorkflowRunResponse]:
        """
        Creates a project and generates a narrated video from a prompt or script. Returns immediately with a workflow run id; poll or subscribe to webhooks for completion.

        Parameters
        ----------
        script : str
            The narration script, used verbatim. This exact text is narrated and turned into a video — it is not rewritten or expanded.

        visual_style : WorkflowVisualStyle

        aspect_ratio : typing.Optional[AspectRatio]

        visual_pacing : typing.Optional[VisualPacing]

        language : typing.Optional[str]
            Output language as a BCP-47 code (e.g. `en`, `es`, `fr`). Defaults to English.

        voice_id : typing.Optional[str]
            Voice id from `GET /v1/resources/tts-voices` (e.g. `vg_voic_...`). A default voice is used when omitted. Any voice may be used here, including voices where `supportsDirectToolExecution` is false.

        voice_speed : typing.Optional[float]
            Speech rate multiplier. Defaults to the voice's default speed.

        avatar_presenter_id : typing.Optional[str]
            Optional avatar presenter id from `GET /v1/resources/avatar-presenters` (e.g. `vg_pres_...`). When set, the narration is delivered by a talking-head presenter avatar. Pass your `voiceId` to that endpoint to list presenters sorted by best match for the voice. Omit for a standard voiceover with no presenter.

        featured_b_roll_file_ids : typing.Optional[typing.Sequence[str]]
            Optional file ids of images or videos to feature as b-roll (e.g. `["vg_file_..."]`). Upload files first via `POST /v1/files/upload`. Only image and video files are accepted.

        workflow_agent_context : typing.Optional[str]
            Optional production notes for the AI that builds the video — visual direction that should not appear in the spoken narration (e.g. on-screen code or text to display, specific b-roll to feature, or scene-by-scene staging). Never spoken; keep the narration itself in `script`.

        remix_actions : typing.Optional[typing.Sequence[RemixAction]]
            Optional edits applied to the project after the video is built, in order. Each action runs asynchronously; the response returns one remix action id per action. Recommended for script-to-video: `ENABLE_CAPTIONS` to show and style captions, `SET_BACKGROUND_MUSIC` to add a music bed, `ADD_TRANSITIONS` to stamp transitions between sections, and `SET_LOGO` to overlay a logo (this workflow has no native caption-style or logo fields). `EDIT_WITH_AGENT` applies open-ended natural-language edits. See the [Remix actions](/remix-actions) guide.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartWorkflowRunResponse]
            Workflow run accepted.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/workflows/script-to-video",
            method="POST",
            json={
                "script": script,
                "aspectRatio": convert_and_respect_annotation_metadata(
                    object_=aspect_ratio, annotation=AspectRatio, direction="write"
                ),
                "visualStyle": convert_and_respect_annotation_metadata(
                    object_=visual_style, annotation=WorkflowVisualStyle, direction="write"
                ),
                "visualPacing": visual_pacing,
                "language": language,
                "voiceId": voice_id,
                "voiceSpeed": voice_speed,
                "avatarPresenterId": avatar_presenter_id,
                "featuredBRollFileIds": featured_b_roll_file_ids,
                "workflowAgentContext": workflow_agent_context,
                "remixActions": convert_and_respect_annotation_metadata(
                    object_=remix_actions, annotation=typing.Sequence[RemixAction], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartWorkflowRunResponse,
                    parse_obj_as(
                        type_=StartWorkflowRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def add_visuals_narrations_and_captions_to_script(
        self,
        *,
        script: str,
        visual_style: WorkflowVisualStyle,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        visual_pacing: typing.Optional[VisualPacing] = OMIT,
        language: typing.Optional[str] = OMIT,
        voice_id: typing.Optional[str] = OMIT,
        voice_speed: typing.Optional[float] = OMIT,
        avatar_presenter_id: typing.Optional[str] = OMIT,
        featured_b_roll_file_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        workflow_agent_context: typing.Optional[str] = OMIT,
        remix_actions: typing.Optional[typing.Sequence[RemixAction]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[StartWorkflowRunResponse]:
        """
        Legacy alias for `POST /v1/workflows/script-to-video`. Use that endpoint instead.

        Parameters
        ----------
        script : str
            The narration script, used verbatim. This exact text is narrated and turned into a video — it is not rewritten or expanded.

        visual_style : WorkflowVisualStyle

        aspect_ratio : typing.Optional[AspectRatio]

        visual_pacing : typing.Optional[VisualPacing]

        language : typing.Optional[str]
            Output language as a BCP-47 code (e.g. `en`, `es`, `fr`). Defaults to English.

        voice_id : typing.Optional[str]
            Voice id from `GET /v1/resources/tts-voices` (e.g. `vg_voic_...`). A default voice is used when omitted. Any voice may be used here, including voices where `supportsDirectToolExecution` is false.

        voice_speed : typing.Optional[float]
            Speech rate multiplier. Defaults to the voice's default speed.

        avatar_presenter_id : typing.Optional[str]
            Optional avatar presenter id from `GET /v1/resources/avatar-presenters` (e.g. `vg_pres_...`). When set, the narration is delivered by a talking-head presenter avatar. Pass your `voiceId` to that endpoint to list presenters sorted by best match for the voice. Omit for a standard voiceover with no presenter.

        featured_b_roll_file_ids : typing.Optional[typing.Sequence[str]]
            Optional file ids of images or videos to feature as b-roll (e.g. `["vg_file_..."]`). Upload files first via `POST /v1/files/upload`. Only image and video files are accepted.

        workflow_agent_context : typing.Optional[str]
            Optional production notes for the AI that builds the video — visual direction that should not appear in the spoken narration (e.g. on-screen code or text to display, specific b-roll to feature, or scene-by-scene staging). Never spoken; keep the narration itself in `script`.

        remix_actions : typing.Optional[typing.Sequence[RemixAction]]
            Optional edits applied to the project after the video is built, in order. Each action runs asynchronously; the response returns one remix action id per action. Recommended for script-to-video: `ENABLE_CAPTIONS` to show and style captions, `SET_BACKGROUND_MUSIC` to add a music bed, `ADD_TRANSITIONS` to stamp transitions between sections, and `SET_LOGO` to overlay a logo (this workflow has no native caption-style or logo fields). `EDIT_WITH_AGENT` applies open-ended natural-language edits. See the [Remix actions](/remix-actions) guide.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartWorkflowRunResponse]
            Workflow run accepted.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/workflows/add-visuals-narrations-and-captions-to-script",
            method="POST",
            json={
                "script": script,
                "aspectRatio": convert_and_respect_annotation_metadata(
                    object_=aspect_ratio, annotation=AspectRatio, direction="write"
                ),
                "visualStyle": convert_and_respect_annotation_metadata(
                    object_=visual_style, annotation=WorkflowVisualStyle, direction="write"
                ),
                "visualPacing": visual_pacing,
                "language": language,
                "voiceId": voice_id,
                "voiceSpeed": voice_speed,
                "avatarPresenterId": avatar_presenter_id,
                "featuredBRollFileIds": featured_b_roll_file_ids,
                "workflowAgentContext": workflow_agent_context,
                "remixActions": convert_and_respect_annotation_metadata(
                    object_=remix_actions, annotation=typing.Sequence[RemixAction], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartWorkflowRunResponse,
                    parse_obj_as(
                        type_=StartWorkflowRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def voiceover_to_video(
        self,
        *,
        file_id: str,
        visual_style: WorkflowVisualStyle,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        visual_pacing: typing.Optional[VisualPacing] = OMIT,
        language: typing.Optional[str] = OMIT,
        caption_style: typing.Optional[WorkflowCaptionStyle] = OMIT,
        logo_file_id: typing.Optional[str] = OMIT,
        workflow_agent_context: typing.Optional[str] = OMIT,
        remix_actions: typing.Optional[typing.Sequence[RemixAction]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[StartWorkflowRunResponse]:
        """
        Creates a project from an uploaded voiceover file and generates a video with matching b-roll. Upload the voiceover via the files API first.

        Parameters
        ----------
        file_id : str
            Opaque file id of an uploaded voiceover audio file (e.g. `vg_file_...`). Upload the file first via `POST /v1/files/upload`.

        visual_style : WorkflowVisualStyle

        aspect_ratio : typing.Optional[AspectRatio]

        visual_pacing : typing.Optional[VisualPacing]

        language : typing.Optional[str]
            Output language as a BCP-47 code (e.g. `en`, `es`, `fr`). Defaults to English.

        caption_style : typing.Optional[WorkflowCaptionStyle]
            Caption styling. Omit to use the default style with captions shown. Pass an object to override individual style fields (any omitted field uses the default). Pass `null` to hide captions entirely.

        logo_file_id : typing.Optional[str]
            Optional file id of an uploaded logo image to overlay on the video (e.g. `vg_file_...`). Upload the image first via `POST /v1/files/upload`. Only image files are accepted.

        workflow_agent_context : typing.Optional[str]
            Optional production notes for the AI that builds the video — visual direction for how to illustrate the voiceover (e.g. on-screen code or text to display, specific b-roll to feature, or scene-by-scene staging). Never spoken; does not change the uploaded voiceover audio or its transcript.

        remix_actions : typing.Optional[typing.Sequence[RemixAction]]
            Optional edits applied to the project after the video is built, in order. Each action runs asynchronously; the response returns one remix action id per action. Captions and a logo are set with the `captionStyle` and `logoFileId` request fields above; recommended remix actions here are `SET_BACKGROUND_MUSIC` for a music bed, `ADD_TRANSITIONS` to stamp transitions between sections and assets, and `EDIT_WITH_AGENT` for open-ended natural-language edits. See the [Remix actions](/remix-actions) guide.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartWorkflowRunResponse]
            Workflow run accepted.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/workflows/voiceover-to-video",
            method="POST",
            json={
                "fileId": file_id,
                "aspectRatio": convert_and_respect_annotation_metadata(
                    object_=aspect_ratio, annotation=AspectRatio, direction="write"
                ),
                "visualStyle": convert_and_respect_annotation_metadata(
                    object_=visual_style, annotation=WorkflowVisualStyle, direction="write"
                ),
                "visualPacing": visual_pacing,
                "language": language,
                "captionStyle": convert_and_respect_annotation_metadata(
                    object_=caption_style, annotation=typing.Optional[WorkflowCaptionStyle], direction="write"
                ),
                "logoFileId": logo_file_id,
                "workflowAgentContext": workflow_agent_context,
                "remixActions": convert_and_respect_annotation_metadata(
                    object_=remix_actions, annotation=typing.Sequence[RemixAction], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartWorkflowRunResponse,
                    parse_obj_as(
                        type_=StartWorkflowRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def add_visuals_and_captions_to_voiceover(
        self,
        *,
        file_id: str,
        visual_style: WorkflowVisualStyle,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        visual_pacing: typing.Optional[VisualPacing] = OMIT,
        language: typing.Optional[str] = OMIT,
        caption_style: typing.Optional[WorkflowCaptionStyle] = OMIT,
        logo_file_id: typing.Optional[str] = OMIT,
        workflow_agent_context: typing.Optional[str] = OMIT,
        remix_actions: typing.Optional[typing.Sequence[RemixAction]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[StartWorkflowRunResponse]:
        """
        Legacy alias for `POST /v1/workflows/voiceover-to-video`. Use that endpoint instead.

        Parameters
        ----------
        file_id : str
            Opaque file id of an uploaded voiceover audio file (e.g. `vg_file_...`). Upload the file first via `POST /v1/files/upload`.

        visual_style : WorkflowVisualStyle

        aspect_ratio : typing.Optional[AspectRatio]

        visual_pacing : typing.Optional[VisualPacing]

        language : typing.Optional[str]
            Output language as a BCP-47 code (e.g. `en`, `es`, `fr`). Defaults to English.

        caption_style : typing.Optional[WorkflowCaptionStyle]
            Caption styling. Omit to use the default style with captions shown. Pass an object to override individual style fields (any omitted field uses the default). Pass `null` to hide captions entirely.

        logo_file_id : typing.Optional[str]
            Optional file id of an uploaded logo image to overlay on the video (e.g. `vg_file_...`). Upload the image first via `POST /v1/files/upload`. Only image files are accepted.

        workflow_agent_context : typing.Optional[str]
            Optional production notes for the AI that builds the video — visual direction for how to illustrate the voiceover (e.g. on-screen code or text to display, specific b-roll to feature, or scene-by-scene staging). Never spoken; does not change the uploaded voiceover audio or its transcript.

        remix_actions : typing.Optional[typing.Sequence[RemixAction]]
            Optional edits applied to the project after the video is built, in order. Each action runs asynchronously; the response returns one remix action id per action. Captions and a logo are set with the `captionStyle` and `logoFileId` request fields above; recommended remix actions here are `SET_BACKGROUND_MUSIC` for a music bed, `ADD_TRANSITIONS` to stamp transitions between sections and assets, and `EDIT_WITH_AGENT` for open-ended natural-language edits. See the [Remix actions](/remix-actions) guide.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartWorkflowRunResponse]
            Workflow run accepted.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/workflows/add-visuals-and-captions-to-voiceover",
            method="POST",
            json={
                "fileId": file_id,
                "aspectRatio": convert_and_respect_annotation_metadata(
                    object_=aspect_ratio, annotation=AspectRatio, direction="write"
                ),
                "visualStyle": convert_and_respect_annotation_metadata(
                    object_=visual_style, annotation=WorkflowVisualStyle, direction="write"
                ),
                "visualPacing": visual_pacing,
                "language": language,
                "captionStyle": convert_and_respect_annotation_metadata(
                    object_=caption_style, annotation=typing.Optional[WorkflowCaptionStyle], direction="write"
                ),
                "logoFileId": logo_file_id,
                "workflowAgentContext": workflow_agent_context,
                "remixActions": convert_and_respect_annotation_metadata(
                    object_=remix_actions, annotation=typing.Sequence[RemixAction], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartWorkflowRunResponse,
                    parse_obj_as(
                        type_=StartWorkflowRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def slideshow_to_video(
        self,
        *,
        file_id: str,
        slide_scripts: typing.Optional[typing.Sequence[str]] = OMIT,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        language: typing.Optional[str] = OMIT,
        voice_id: typing.Optional[str] = OMIT,
        voice_speed: typing.Optional[float] = OMIT,
        avatar_presenter_id: typing.Optional[str] = OMIT,
        caption_style: typing.Optional[WorkflowCaptionStyle] = OMIT,
        logo_file_id: typing.Optional[str] = OMIT,
        remix_actions: typing.Optional[typing.Sequence[RemixAction]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[StartWorkflowRunResponse]:
        """
        Creates a project from an uploaded PDF or PowerPoint file and generates an AI-narrated video walking through each slide. Upload the file via `POST /v1/files/upload` first.

        Parameters
        ----------
        file_id : str
            Opaque file id of an uploaded PDF or PowerPoint file (e.g. `vg_file_...`). Upload the file first via `POST /v1/files/upload`.

        slide_scripts : typing.Optional[typing.Sequence[str]]
            Optional per-slide narration, in slide order, applied by index: each slide uses its matching entry, and an empty string makes that slide silent. If you provide fewer entries than slides, the remaining slides are silent; extra entries are ignored. Omit this field entirely to narrate each slide from its speaker notes in the uploaded file. To guarantee no narration on any slide, pass an empty array.

        aspect_ratio : typing.Optional[AspectRatio]

        language : typing.Optional[str]
            Output language as a BCP-47 code (e.g. `en`, `es`, `fr`). Defaults to English.

        voice_id : typing.Optional[str]
            Voice id from `GET /v1/resources/tts-voices` (e.g. `vg_voic_...`). A default voice is used when omitted. Any voice may be used here, including voices where `supportsDirectToolExecution` is false.

        voice_speed : typing.Optional[float]
            Speech rate multiplier. Defaults to the voice's default speed.

        avatar_presenter_id : typing.Optional[str]
            Optional avatar presenter id from `GET /v1/resources/avatar-presenters` (e.g. `vg_pres_...`). When set, the narration is delivered by a talking-head presenter avatar. Pass your `voiceId` to that endpoint to list presenters sorted by best match for the voice. Omit for a standard voiceover with no presenter.

        caption_style : typing.Optional[WorkflowCaptionStyle]
            Caption styling. Omit to use the default style with captions shown. Pass an object to override individual style fields (any omitted field uses the default). Pass `null` to hide captions entirely.

        logo_file_id : typing.Optional[str]
            Optional file id of an uploaded logo image to overlay on the video (e.g. `vg_file_...`). Upload the image first via `POST /v1/files/upload`. Only image files are accepted.

        remix_actions : typing.Optional[typing.Sequence[RemixAction]]
            Optional edits applied to the project after the video is built, in order. Each action runs asynchronously; the response returns one remix action id per action. Captions and a logo are set with the `captionStyle` and `logoFileId` request fields above; recommended remix actions here are `SET_BACKGROUND_MUSIC` for a music bed, `ADD_TRANSITIONS` to stamp transitions between sections and assets, and `EDIT_WITH_AGENT` for open-ended natural-language edits. See the [Remix actions](/remix-actions) guide.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartWorkflowRunResponse]
            Workflow run accepted.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/workflows/slideshow-to-video",
            method="POST",
            json={
                "fileId": file_id,
                "slideScripts": slide_scripts,
                "aspectRatio": convert_and_respect_annotation_metadata(
                    object_=aspect_ratio, annotation=AspectRatio, direction="write"
                ),
                "language": language,
                "voiceId": voice_id,
                "voiceSpeed": voice_speed,
                "avatarPresenterId": avatar_presenter_id,
                "captionStyle": convert_and_respect_annotation_metadata(
                    object_=caption_style, annotation=typing.Optional[WorkflowCaptionStyle], direction="write"
                ),
                "logoFileId": logo_file_id,
                "remixActions": convert_and_respect_annotation_metadata(
                    object_=remix_actions, annotation=typing.Sequence[RemixAction], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartWorkflowRunResponse,
                    parse_obj_as(
                        type_=StartWorkflowRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def add_narration_transitions_and_captions_to_slideshow(
        self,
        *,
        file_id: str,
        slide_scripts: typing.Optional[typing.Sequence[str]] = OMIT,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        language: typing.Optional[str] = OMIT,
        voice_id: typing.Optional[str] = OMIT,
        voice_speed: typing.Optional[float] = OMIT,
        avatar_presenter_id: typing.Optional[str] = OMIT,
        caption_style: typing.Optional[WorkflowCaptionStyle] = OMIT,
        logo_file_id: typing.Optional[str] = OMIT,
        remix_actions: typing.Optional[typing.Sequence[RemixAction]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[StartWorkflowRunResponse]:
        """
        Legacy alias for `POST /v1/workflows/slideshow-to-video`. Use that endpoint instead.

        Parameters
        ----------
        file_id : str
            Opaque file id of an uploaded PDF or PowerPoint file (e.g. `vg_file_...`). Upload the file first via `POST /v1/files/upload`.

        slide_scripts : typing.Optional[typing.Sequence[str]]
            Optional per-slide narration, in slide order, applied by index: each slide uses its matching entry, and an empty string makes that slide silent. If you provide fewer entries than slides, the remaining slides are silent; extra entries are ignored. Omit this field entirely to narrate each slide from its speaker notes in the uploaded file. To guarantee no narration on any slide, pass an empty array.

        aspect_ratio : typing.Optional[AspectRatio]

        language : typing.Optional[str]
            Output language as a BCP-47 code (e.g. `en`, `es`, `fr`). Defaults to English.

        voice_id : typing.Optional[str]
            Voice id from `GET /v1/resources/tts-voices` (e.g. `vg_voic_...`). A default voice is used when omitted. Any voice may be used here, including voices where `supportsDirectToolExecution` is false.

        voice_speed : typing.Optional[float]
            Speech rate multiplier. Defaults to the voice's default speed.

        avatar_presenter_id : typing.Optional[str]
            Optional avatar presenter id from `GET /v1/resources/avatar-presenters` (e.g. `vg_pres_...`). When set, the narration is delivered by a talking-head presenter avatar. Pass your `voiceId` to that endpoint to list presenters sorted by best match for the voice. Omit for a standard voiceover with no presenter.

        caption_style : typing.Optional[WorkflowCaptionStyle]
            Caption styling. Omit to use the default style with captions shown. Pass an object to override individual style fields (any omitted field uses the default). Pass `null` to hide captions entirely.

        logo_file_id : typing.Optional[str]
            Optional file id of an uploaded logo image to overlay on the video (e.g. `vg_file_...`). Upload the image first via `POST /v1/files/upload`. Only image files are accepted.

        remix_actions : typing.Optional[typing.Sequence[RemixAction]]
            Optional edits applied to the project after the video is built, in order. Each action runs asynchronously; the response returns one remix action id per action. Captions and a logo are set with the `captionStyle` and `logoFileId` request fields above; recommended remix actions here are `SET_BACKGROUND_MUSIC` for a music bed, `ADD_TRANSITIONS` to stamp transitions between sections and assets, and `EDIT_WITH_AGENT` for open-ended natural-language edits. See the [Remix actions](/remix-actions) guide.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartWorkflowRunResponse]
            Workflow run accepted.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/workflows/add-narration-transitions-and-captions-to-slideshow",
            method="POST",
            json={
                "fileId": file_id,
                "slideScripts": slide_scripts,
                "aspectRatio": convert_and_respect_annotation_metadata(
                    object_=aspect_ratio, annotation=AspectRatio, direction="write"
                ),
                "language": language,
                "voiceId": voice_id,
                "voiceSpeed": voice_speed,
                "avatarPresenterId": avatar_presenter_id,
                "captionStyle": convert_and_respect_annotation_metadata(
                    object_=caption_style, annotation=typing.Optional[WorkflowCaptionStyle], direction="write"
                ),
                "logoFileId": logo_file_id,
                "remixActions": convert_and_respect_annotation_metadata(
                    object_=remix_actions, annotation=typing.Sequence[RemixAction], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartWorkflowRunResponse,
                    parse_obj_as(
                        type_=StartWorkflowRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def storyboard_to_video(
        self,
        *,
        scenes: typing.Sequence[GenerateStoryboardScene],
        default_generation: typing.Optional[SceneGeneration] = OMIT,
        default_duration_seconds: typing.Optional[int] = OMIT,
        quality: typing.Optional[StoryboardToVideoRequestQuality] = OMIT,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        workflow_agent_context: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[StartWorkflowRunResponse]:
        """
        Creates a project from an ordered list of scenes and generates one section per scene. Each scene is generated from its prompt as either a still image or a video clip; the scenes are then assembled into a single video. Returns immediately with a workflow run id; poll or subscribe to webhooks for completion.

        Parameters
        ----------
        scenes : typing.Sequence[GenerateStoryboardScene]
            Ordered list of scenes. Each scene becomes one section in the final video, in this order.

        default_generation : typing.Optional[SceneGeneration]
            Default generation applied to scenes that don't set their own `generation`. Defaults to AI_IMAGE with no extra style.

        default_duration_seconds : typing.Optional[int]
            Default per-scene duration in seconds for scenes that don't set their own `durationSeconds`. Defaults to 5. For AI_VIDEO scenes this must be a whole number between 1 and 15.

        quality : typing.Optional[StoryboardToVideoRequestQuality]
            Generation quality tier for every scene. LOW is fastest and cheapest; STANDARD balances quality and cost; HIGH is highest quality. Defaults to STANDARD. LOW is not supported for AI_VIDEO scenes: the request is rejected if any scene is generated as a video at LOW quality.

        aspect_ratio : typing.Optional[AspectRatio]

        workflow_agent_context : typing.Optional[str]
            Optional storyboard-wide production notes for the AI that builds the video (e.g. recurring characters or props, a consistent setting, or overall staging guidance). Applies across every scene; per-scene direction goes in each scene's `prompt`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartWorkflowRunResponse]
            Workflow run accepted.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/workflows/storyboard-to-video",
            method="POST",
            json={
                "scenes": convert_and_respect_annotation_metadata(
                    object_=scenes, annotation=typing.Sequence[GenerateStoryboardScene], direction="write"
                ),
                "defaultGeneration": convert_and_respect_annotation_metadata(
                    object_=default_generation, annotation=typing.Optional[SceneGeneration], direction="write"
                ),
                "defaultDurationSeconds": default_duration_seconds,
                "quality": quality,
                "aspectRatio": convert_and_respect_annotation_metadata(
                    object_=aspect_ratio, annotation=AspectRatio, direction="write"
                ),
                "workflowAgentContext": workflow_agent_context,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartWorkflowRunResponse,
                    parse_obj_as(
                        type_=StartWorkflowRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def generate_scenes_from_storyboard(
        self,
        *,
        scenes: typing.Sequence[GenerateStoryboardScene],
        default_generation: typing.Optional[SceneGeneration] = OMIT,
        default_duration_seconds: typing.Optional[int] = OMIT,
        quality: typing.Optional[StoryboardToVideoRequestQuality] = OMIT,
        aspect_ratio: typing.Optional[AspectRatio] = OMIT,
        workflow_agent_context: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[StartWorkflowRunResponse]:
        """
        Legacy alias for `POST /v1/workflows/storyboard-to-video`. Use that endpoint instead.

        Parameters
        ----------
        scenes : typing.Sequence[GenerateStoryboardScene]
            Ordered list of scenes. Each scene becomes one section in the final video, in this order.

        default_generation : typing.Optional[SceneGeneration]
            Default generation applied to scenes that don't set their own `generation`. Defaults to AI_IMAGE with no extra style.

        default_duration_seconds : typing.Optional[int]
            Default per-scene duration in seconds for scenes that don't set their own `durationSeconds`. Defaults to 5. For AI_VIDEO scenes this must be a whole number between 1 and 15.

        quality : typing.Optional[StoryboardToVideoRequestQuality]
            Generation quality tier for every scene. LOW is fastest and cheapest; STANDARD balances quality and cost; HIGH is highest quality. Defaults to STANDARD. LOW is not supported for AI_VIDEO scenes: the request is rejected if any scene is generated as a video at LOW quality.

        aspect_ratio : typing.Optional[AspectRatio]

        workflow_agent_context : typing.Optional[str]
            Optional storyboard-wide production notes for the AI that builds the video (e.g. recurring characters or props, a consistent setting, or overall staging guidance). Applies across every scene; per-scene direction goes in each scene's `prompt`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartWorkflowRunResponse]
            Workflow run accepted.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/workflows/generate-scenes-from-storyboard",
            method="POST",
            json={
                "scenes": convert_and_respect_annotation_metadata(
                    object_=scenes, annotation=typing.Sequence[GenerateStoryboardScene], direction="write"
                ),
                "defaultGeneration": convert_and_respect_annotation_metadata(
                    object_=default_generation, annotation=typing.Optional[SceneGeneration], direction="write"
                ),
                "defaultDurationSeconds": default_duration_seconds,
                "quality": quality,
                "aspectRatio": convert_and_respect_annotation_metadata(
                    object_=aspect_ratio, annotation=AspectRatio, direction="write"
                ),
                "workflowAgentContext": workflow_agent_context,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartWorkflowRunResponse,
                    parse_obj_as(
                        type_=StartWorkflowRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_workflow_run(
        self, workflow_run_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[WorkflowRun]:
        """
        Parameters
        ----------
        workflow_run_id : str
            The workflow run id returned when the workflow was started.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WorkflowRun]
            Current workflow run state.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/workflows/runs/{encode_path_param(workflow_run_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowRun,
                    parse_obj_as(
                        type_=WorkflowRun,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def cancel_workflow_run(
        self, workflow_run_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[StartWorkflowRunResponse]:
        """
        Parameters
        ----------
        workflow_run_id : str
            The workflow run id returned when the workflow was started.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StartWorkflowRunResponse]
            Cancellation request accepted.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/workflows/runs/{encode_path_param(workflow_run_id)}/cancel",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StartWorkflowRunResponse,
                    parse_obj_as(
                        type_=StartWorkflowRunResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
