# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        ApiError,
        ApiErrorRequirement,
        AspectRatio,
        AvatarPresenter,
        AvatarPresenterDisplayableGender,
        AvatarPresenterListResponse,
        ExecutedTool,
        ExecutedToolStatus,
        FileSource,
        FileSourceStatus,
        FileUploadResponse,
        FileUploadWebhookEventName,
        FileUploadWebhookPayload,
        GetFilesResponse,
        ImageAssetRequest,
        PronunciationReplacement,
        SearchFilesResponse,
        SearchFilesResult,
        StartToolExecutionResponse,
        StorageFile,
        StorageFileScope,
        StorageFileType,
        ToolExecutionWebhookEventName,
        ToolExecutionWebhookPayload,
        ToolSuccessResult,
        ToolSuccessResultType,
        TtsVoice,
        TtsVoiceDisplayGender,
        TtsVoiceListResponse,
        VideoAssetRequest,
        WatermarkMode,
        WebhookEndpoint,
        WebhookEndpointListResponse,
        WebhookEventName,
    )
    from . import files, resources, tools, webhooks
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .async_download_file import async_download_file
    from .async_get_hydrated_file import async_get_hydrated_file
    from .async_poll_executed_tool import async_poll_executed_tool
    from .async_upload_file import async_upload_file
    from .client import AsyncVideoGenApi, VideoGenApi
    from .download_file import download_file
    from .environment import VideoGenApiEnvironment
    from .files import CreateFileUploadRequestType
    from .get_hydrated_file import get_hydrated_file
    from .poll_executed_tool import poll_executed_tool
    from .upload_file import upload_file
    from .verify_webhook_signature import WebhookEvent, verify_webhook_signature
    from .version import __version__
_dynamic_imports: typing.Dict[str, str] = {
    "ApiError": ".types",
    "ApiErrorRequirement": ".types",
    "AspectRatio": ".types",
    "AsyncVideoGenApi": ".client",
    "AvatarPresenter": ".types",
    "AvatarPresenterDisplayableGender": ".types",
    "AvatarPresenterListResponse": ".types",
    "CreateFileUploadRequestType": ".files",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "ExecutedTool": ".types",
    "ExecutedToolStatus": ".types",
    "FileSource": ".types",
    "FileSourceStatus": ".types",
    "FileUploadResponse": ".types",
    "FileUploadWebhookEventName": ".types",
    "FileUploadWebhookPayload": ".types",
    "GetFilesResponse": ".types",
    "ImageAssetRequest": ".types",
    "PronunciationReplacement": ".types",
    "SearchFilesResponse": ".types",
    "SearchFilesResult": ".types",
    "StartToolExecutionResponse": ".types",
    "StorageFile": ".types",
    "StorageFileScope": ".types",
    "StorageFileType": ".types",
    "ToolExecutionWebhookEventName": ".types",
    "ToolExecutionWebhookPayload": ".types",
    "ToolSuccessResult": ".types",
    "ToolSuccessResultType": ".types",
    "TtsVoice": ".types",
    "TtsVoiceDisplayGender": ".types",
    "TtsVoiceListResponse": ".types",
    "VideoAssetRequest": ".types",
    "VideoGenApi": ".client",
    "VideoGenApiEnvironment": ".environment",
    "WatermarkMode": ".types",
    "WebhookEndpoint": ".types",
    "WebhookEndpointListResponse": ".types",
    "WebhookEvent": ".verify_webhook_signature",
    "WebhookEventName": ".types",
    "__version__": ".version",
    "async_download_file": ".async_download_file",
    "async_get_hydrated_file": ".async_get_hydrated_file",
    "async_poll_executed_tool": ".async_poll_executed_tool",
    "async_upload_file": ".async_upload_file",
    "download_file": ".download_file",
    "files": ".files",
    "get_hydrated_file": ".get_hydrated_file",
    "poll_executed_tool": ".poll_executed_tool",
    "resources": ".resources",
    "tools": ".tools",
    "upload_file": ".upload_file",
    "verify_webhook_signature": ".verify_webhook_signature",
    "webhooks": ".webhooks",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ApiError",
    "ApiErrorRequirement",
    "AspectRatio",
    "AsyncVideoGenApi",
    "AvatarPresenter",
    "AvatarPresenterDisplayableGender",
    "AvatarPresenterListResponse",
    "CreateFileUploadRequestType",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "ExecutedTool",
    "ExecutedToolStatus",
    "FileSource",
    "FileSourceStatus",
    "FileUploadResponse",
    "FileUploadWebhookEventName",
    "FileUploadWebhookPayload",
    "GetFilesResponse",
    "ImageAssetRequest",
    "PronunciationReplacement",
    "SearchFilesResponse",
    "SearchFilesResult",
    "StartToolExecutionResponse",
    "StorageFile",
    "StorageFileScope",
    "StorageFileType",
    "ToolExecutionWebhookEventName",
    "ToolExecutionWebhookPayload",
    "ToolSuccessResult",
    "ToolSuccessResultType",
    "TtsVoice",
    "TtsVoiceDisplayGender",
    "TtsVoiceListResponse",
    "VideoAssetRequest",
    "VideoGenApi",
    "VideoGenApiEnvironment",
    "WatermarkMode",
    "WebhookEndpoint",
    "WebhookEndpointListResponse",
    "WebhookEvent",
    "WebhookEventName",
    "__version__",
    "async_download_file",
    "async_get_hydrated_file",
    "async_poll_executed_tool",
    "async_upload_file",
    "download_file",
    "files",
    "get_hydrated_file",
    "poll_executed_tool",
    "resources",
    "tools",
    "upload_file",
    "verify_webhook_signature",
    "webhooks",
]
