# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..types.assistant_turn_response import AssistantTurnResponse
from .types.act_on_assistant_action_request_decision import ActOnAssistantActionRequestDecision
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawAssistantClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def start_assistant_chat(
        self,
        *,
        message: str,
        force_workflow_suggestion: typing.Optional[bool] = OMIT,
        auto_generate: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[AssistantTurnResponse]:
        """
        Creates a new project and sends the first message to the VideoGen AI assistant, exactly like typing into the assistant on a new project in the app. Synchronous: the response includes the assistant's reply, any workflow suggestions it offered, and a `projectUrl` to open the project in the app. Continue the conversation with `POST /v1/assistant/chats/{projectId}/messages`.

        Parameters
        ----------
        message : str
            The first message to send to the assistant, exactly as a person would type it into the assistant on a new project.

        force_workflow_suggestion : typing.Optional[bool]
            When true, the assistant always responds with at least one workflow suggestion (the fastest way to get a starting point). When false, the assistant decides whether to suggest a workflow or just reply.

        auto_generate : typing.Optional[bool]
            When true, the assistant picks the best workflow for the message and immediately starts generating, skipping the suggestion step. The response's `status` is `generating` and `generation` carries the run to poll. When false, nothing generates until you act on a suggestion or plan.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[AssistantTurnResponse]
            The assistant's reply.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/assistant/chats",
            method="POST",
            json={
                "message": message,
                "forceWorkflowSuggestion": force_workflow_suggestion,
                "autoGenerate": auto_generate,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AssistantTurnResponse,
                    parse_obj_as(
                        type_=AssistantTurnResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def send_assistant_message(
        self, project_id: str, *, message: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[AssistantTurnResponse]:
        """
        Sends a follow-up message to the assistant in an existing project chat started with `POST /v1/assistant/chats`. Synchronous: the response includes the assistant's reply and any actions it offered.

        Parameters
        ----------
        project_id : str
            The project id (e.g. `vg_proj_...`).

        message : str
            The message to send to the assistant in this project chat.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[AssistantTurnResponse]
            The assistant's reply.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/assistant/chats/{encode_path_param(project_id)}/messages",
            method="POST",
            json={
                "message": message,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AssistantTurnResponse,
                    parse_obj_as(
                        type_=AssistantTurnResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def act_on_assistant_action(
        self,
        project_id: str,
        assistant_action_id: str,
        *,
        decision: typing.Optional[ActOnAssistantActionRequestDecision] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[AssistantTurnResponse]:
        """
        Acts on an actionable widget the assistant offered on a prior turn. Reference the action by its `assistantActionId` from a prior `AssistantTurnResponse`. Today this accepts a workflow suggestion: `APPROVE` (the default) applies the suggested workflow and immediately starts generating — the response's `status` is `generating` and `generation` carries the run to poll — while `REJECT` returns the offering turn unchanged. Every other action has `requiresApp` set to true and can only be completed in the web app; open `projectUrl` instead.

        Parameters
        ----------
        project_id : str
            The project id (e.g. `vg_proj_...`).

        assistant_action_id : str
            The `assistantActionId` of the action to act on, from a prior `AssistantTurnResponse`.

        decision : typing.Optional[ActOnAssistantActionRequestDecision]
            Whether to approve (apply) or reject the action. Defaults to `APPROVE`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[AssistantTurnResponse]
            The assistant's reply after acting on the action.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/assistant/chats/{encode_path_param(project_id)}/actions/{encode_path_param(assistant_action_id)}",
            method="POST",
            json={
                "decision": decision,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AssistantTurnResponse,
                    parse_obj_as(
                        type_=AssistantTurnResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawAssistantClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def start_assistant_chat(
        self,
        *,
        message: str,
        force_workflow_suggestion: typing.Optional[bool] = OMIT,
        auto_generate: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[AssistantTurnResponse]:
        """
        Creates a new project and sends the first message to the VideoGen AI assistant, exactly like typing into the assistant on a new project in the app. Synchronous: the response includes the assistant's reply, any workflow suggestions it offered, and a `projectUrl` to open the project in the app. Continue the conversation with `POST /v1/assistant/chats/{projectId}/messages`.

        Parameters
        ----------
        message : str
            The first message to send to the assistant, exactly as a person would type it into the assistant on a new project.

        force_workflow_suggestion : typing.Optional[bool]
            When true, the assistant always responds with at least one workflow suggestion (the fastest way to get a starting point). When false, the assistant decides whether to suggest a workflow or just reply.

        auto_generate : typing.Optional[bool]
            When true, the assistant picks the best workflow for the message and immediately starts generating, skipping the suggestion step. The response's `status` is `generating` and `generation` carries the run to poll. When false, nothing generates until you act on a suggestion or plan.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[AssistantTurnResponse]
            The assistant's reply.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/assistant/chats",
            method="POST",
            json={
                "message": message,
                "forceWorkflowSuggestion": force_workflow_suggestion,
                "autoGenerate": auto_generate,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AssistantTurnResponse,
                    parse_obj_as(
                        type_=AssistantTurnResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def send_assistant_message(
        self, project_id: str, *, message: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[AssistantTurnResponse]:
        """
        Sends a follow-up message to the assistant in an existing project chat started with `POST /v1/assistant/chats`. Synchronous: the response includes the assistant's reply and any actions it offered.

        Parameters
        ----------
        project_id : str
            The project id (e.g. `vg_proj_...`).

        message : str
            The message to send to the assistant in this project chat.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[AssistantTurnResponse]
            The assistant's reply.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/assistant/chats/{encode_path_param(project_id)}/messages",
            method="POST",
            json={
                "message": message,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AssistantTurnResponse,
                    parse_obj_as(
                        type_=AssistantTurnResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def act_on_assistant_action(
        self,
        project_id: str,
        assistant_action_id: str,
        *,
        decision: typing.Optional[ActOnAssistantActionRequestDecision] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[AssistantTurnResponse]:
        """
        Acts on an actionable widget the assistant offered on a prior turn. Reference the action by its `assistantActionId` from a prior `AssistantTurnResponse`. Today this accepts a workflow suggestion: `APPROVE` (the default) applies the suggested workflow and immediately starts generating — the response's `status` is `generating` and `generation` carries the run to poll — while `REJECT` returns the offering turn unchanged. Every other action has `requiresApp` set to true and can only be completed in the web app; open `projectUrl` instead.

        Parameters
        ----------
        project_id : str
            The project id (e.g. `vg_proj_...`).

        assistant_action_id : str
            The `assistantActionId` of the action to act on, from a prior `AssistantTurnResponse`.

        decision : typing.Optional[ActOnAssistantActionRequestDecision]
            Whether to approve (apply) or reject the action. Defaults to `APPROVE`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[AssistantTurnResponse]
            The assistant's reply after acting on the action.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/assistant/chats/{encode_path_param(project_id)}/actions/{encode_path_param(assistant_action_id)}",
            method="POST",
            json={
                "decision": decision,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AssistantTurnResponse,
                    parse_obj_as(
                        type_=AssistantTurnResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
