# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .api_error import ApiError
    from .api_error_requirement import ApiErrorRequirement
    from .aspect_ratio import AspectRatio
    from .avatar_presenter import AvatarPresenter
    from .avatar_presenter_displayable_gender import AvatarPresenterDisplayableGender
    from .avatar_presenter_list_response import AvatarPresenterListResponse
    from .entity import Entity
    from .entity_actor_config import EntityActorConfig
    from .entity_archive_response import EntityArchiveResponse
    from .entity_entity_type import EntityEntityType
    from .entity_reference import EntityReference
    from .executed_tool import ExecutedTool
    from .executed_tool_status import ExecutedToolStatus
    from .export_project_quality import ExportProjectQuality
    from .export_project_response import ExportProjectResponse
    from .file_analysis_metadata import FileAnalysisMetadata
    from .file_analysis_metadata_analysis_loading_state import FileAnalysisMetadataAnalysisLoadingState
    from .file_source import FileSource
    from .file_source_status import FileSourceStatus
    from .file_upload_response import FileUploadResponse
    from .file_upload_webhook_event_name import FileUploadWebhookEventName
    from .file_upload_webhook_payload import FileUploadWebhookPayload
    from .generate_storyboard_scene import GenerateStoryboardScene
    from .generate_text_response import GenerateTextResponse
    from .get_files_response import GetFilesResponse
    from .image_asset_request import ImageAssetRequest
    from .image_model_mode import ImageModelMode
    from .list_entities_response import ListEntitiesResponse
    from .list_projects_response import ListProjectsResponse
    from .list_remix_actions_response import ListRemixActionsResponse
    from .project_export import ProjectExport
    from .project_export_status import ProjectExportStatus
    from .project_response import ProjectResponse
    from .project_response_status import ProjectResponseStatus
    from .pronunciation_replacement import PronunciationReplacement
    from .remix_action import (
        RemixAction,
        RemixAction_AddTransitions,
        RemixAction_DisableCaptions,
        RemixAction_EditWithAgent,
        RemixAction_EnableCaptions,
        RemixAction_SetBackgroundMusic,
        RemixAction_SetLogo,
    )
    from .remix_action_add_transitions import RemixActionAddTransitions
    from .remix_action_disable_captions import RemixActionDisableCaptions
    from .remix_action_edit_with_agent import RemixActionEditWithAgent
    from .remix_action_edit_with_agent_mode import RemixActionEditWithAgentMode
    from .remix_action_enable_captions import RemixActionEnableCaptions
    from .remix_action_run import RemixActionRun
    from .remix_action_set_background_music import RemixActionSetBackgroundMusic
    from .remix_action_set_logo import RemixActionSetLogo
    from .remix_action_set_logo_position import RemixActionSetLogoPosition
    from .remix_action_status import RemixActionStatus
    from .remix_action_type import RemixActionType
    from .remix_project_response import RemixProjectResponse
    from .remix_transition_style import RemixTransitionStyle
    from .scene_generation import SceneGeneration
    from .scene_generation_type import SceneGenerationType
    from .script_to_video_request import ScriptToVideoRequest
    from .search_files_response import SearchFilesResponse
    from .search_files_result import SearchFilesResult
    from .slideshow_to_video_request import SlideshowToVideoRequest
    from .start_tool_execution_response import StartToolExecutionResponse
    from .start_workflow_run_response import StartWorkflowRunResponse
    from .storage_file import StorageFile
    from .storage_file_scope import StorageFileScope
    from .storage_file_type import StorageFileType
    from .storyboard_to_video_request import StoryboardToVideoRequest
    from .storyboard_to_video_request_quality import StoryboardToVideoRequestQuality
    from .tool_execution_webhook_event_name import ToolExecutionWebhookEventName
    from .tool_execution_webhook_payload import ToolExecutionWebhookPayload
    from .tool_success_result import ToolSuccessResult
    from .tool_success_result_type import ToolSuccessResultType
    from .tts_voice import TtsVoice
    from .tts_voice_display_gender import TtsVoiceDisplayGender
    from .tts_voice_list_response import TtsVoiceListResponse
    from .video_asset_request import VideoAssetRequest
    from .video_model_mode import VideoModelMode
    from .visual_pacing import VisualPacing
    from .voiceover_to_video_request import VoiceoverToVideoRequest
    from .watermark_mode import WatermarkMode
    from .webhook_endpoint import WebhookEndpoint
    from .webhook_endpoint_list_response import WebhookEndpointListResponse
    from .webhook_event_name import WebhookEventName
    from .workflow_caption_background_style import WorkflowCaptionBackgroundStyle
    from .workflow_caption_background_style_type import WorkflowCaptionBackgroundStyleType
    from .workflow_caption_style import WorkflowCaptionStyle
    from .workflow_caption_style_text_justification import WorkflowCaptionStyleTextJustification
    from .workflow_caption_style_vertical_alignment import WorkflowCaptionStyleVerticalAlignment
    from .workflow_rgb_color import WorkflowRgbColor
    from .workflow_run import WorkflowRun
    from .workflow_run_status import WorkflowRunStatus
    from .workflow_run_webhook_event_name import WorkflowRunWebhookEventName
    from .workflow_run_webhook_payload import WorkflowRunWebhookPayload
    from .workflow_type import WorkflowType
    from .workflow_visual_style import WorkflowVisualStyle
    from .workflow_visual_style_type import WorkflowVisualStyleType
_dynamic_imports: typing.Dict[str, str] = {
    "ApiError": ".api_error",
    "ApiErrorRequirement": ".api_error_requirement",
    "AspectRatio": ".aspect_ratio",
    "AvatarPresenter": ".avatar_presenter",
    "AvatarPresenterDisplayableGender": ".avatar_presenter_displayable_gender",
    "AvatarPresenterListResponse": ".avatar_presenter_list_response",
    "Entity": ".entity",
    "EntityActorConfig": ".entity_actor_config",
    "EntityArchiveResponse": ".entity_archive_response",
    "EntityEntityType": ".entity_entity_type",
    "EntityReference": ".entity_reference",
    "ExecutedTool": ".executed_tool",
    "ExecutedToolStatus": ".executed_tool_status",
    "ExportProjectQuality": ".export_project_quality",
    "ExportProjectResponse": ".export_project_response",
    "FileAnalysisMetadata": ".file_analysis_metadata",
    "FileAnalysisMetadataAnalysisLoadingState": ".file_analysis_metadata_analysis_loading_state",
    "FileSource": ".file_source",
    "FileSourceStatus": ".file_source_status",
    "FileUploadResponse": ".file_upload_response",
    "FileUploadWebhookEventName": ".file_upload_webhook_event_name",
    "FileUploadWebhookPayload": ".file_upload_webhook_payload",
    "GenerateStoryboardScene": ".generate_storyboard_scene",
    "GenerateTextResponse": ".generate_text_response",
    "GetFilesResponse": ".get_files_response",
    "ImageAssetRequest": ".image_asset_request",
    "ImageModelMode": ".image_model_mode",
    "ListEntitiesResponse": ".list_entities_response",
    "ListProjectsResponse": ".list_projects_response",
    "ListRemixActionsResponse": ".list_remix_actions_response",
    "ProjectExport": ".project_export",
    "ProjectExportStatus": ".project_export_status",
    "ProjectResponse": ".project_response",
    "ProjectResponseStatus": ".project_response_status",
    "PronunciationReplacement": ".pronunciation_replacement",
    "RemixAction": ".remix_action",
    "RemixActionAddTransitions": ".remix_action_add_transitions",
    "RemixActionDisableCaptions": ".remix_action_disable_captions",
    "RemixActionEditWithAgent": ".remix_action_edit_with_agent",
    "RemixActionEditWithAgentMode": ".remix_action_edit_with_agent_mode",
    "RemixActionEnableCaptions": ".remix_action_enable_captions",
    "RemixActionRun": ".remix_action_run",
    "RemixActionSetBackgroundMusic": ".remix_action_set_background_music",
    "RemixActionSetLogo": ".remix_action_set_logo",
    "RemixActionSetLogoPosition": ".remix_action_set_logo_position",
    "RemixActionStatus": ".remix_action_status",
    "RemixActionType": ".remix_action_type",
    "RemixAction_AddTransitions": ".remix_action",
    "RemixAction_DisableCaptions": ".remix_action",
    "RemixAction_EditWithAgent": ".remix_action",
    "RemixAction_EnableCaptions": ".remix_action",
    "RemixAction_SetBackgroundMusic": ".remix_action",
    "RemixAction_SetLogo": ".remix_action",
    "RemixProjectResponse": ".remix_project_response",
    "RemixTransitionStyle": ".remix_transition_style",
    "SceneGeneration": ".scene_generation",
    "SceneGenerationType": ".scene_generation_type",
    "ScriptToVideoRequest": ".script_to_video_request",
    "SearchFilesResponse": ".search_files_response",
    "SearchFilesResult": ".search_files_result",
    "SlideshowToVideoRequest": ".slideshow_to_video_request",
    "StartToolExecutionResponse": ".start_tool_execution_response",
    "StartWorkflowRunResponse": ".start_workflow_run_response",
    "StorageFile": ".storage_file",
    "StorageFileScope": ".storage_file_scope",
    "StorageFileType": ".storage_file_type",
    "StoryboardToVideoRequest": ".storyboard_to_video_request",
    "StoryboardToVideoRequestQuality": ".storyboard_to_video_request_quality",
    "ToolExecutionWebhookEventName": ".tool_execution_webhook_event_name",
    "ToolExecutionWebhookPayload": ".tool_execution_webhook_payload",
    "ToolSuccessResult": ".tool_success_result",
    "ToolSuccessResultType": ".tool_success_result_type",
    "TtsVoice": ".tts_voice",
    "TtsVoiceDisplayGender": ".tts_voice_display_gender",
    "TtsVoiceListResponse": ".tts_voice_list_response",
    "VideoAssetRequest": ".video_asset_request",
    "VideoModelMode": ".video_model_mode",
    "VisualPacing": ".visual_pacing",
    "VoiceoverToVideoRequest": ".voiceover_to_video_request",
    "WatermarkMode": ".watermark_mode",
    "WebhookEndpoint": ".webhook_endpoint",
    "WebhookEndpointListResponse": ".webhook_endpoint_list_response",
    "WebhookEventName": ".webhook_event_name",
    "WorkflowCaptionBackgroundStyle": ".workflow_caption_background_style",
    "WorkflowCaptionBackgroundStyleType": ".workflow_caption_background_style_type",
    "WorkflowCaptionStyle": ".workflow_caption_style",
    "WorkflowCaptionStyleTextJustification": ".workflow_caption_style_text_justification",
    "WorkflowCaptionStyleVerticalAlignment": ".workflow_caption_style_vertical_alignment",
    "WorkflowRgbColor": ".workflow_rgb_color",
    "WorkflowRun": ".workflow_run",
    "WorkflowRunStatus": ".workflow_run_status",
    "WorkflowRunWebhookEventName": ".workflow_run_webhook_event_name",
    "WorkflowRunWebhookPayload": ".workflow_run_webhook_payload",
    "WorkflowType": ".workflow_type",
    "WorkflowVisualStyle": ".workflow_visual_style",
    "WorkflowVisualStyleType": ".workflow_visual_style_type",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ApiError",
    "ApiErrorRequirement",
    "AspectRatio",
    "AvatarPresenter",
    "AvatarPresenterDisplayableGender",
    "AvatarPresenterListResponse",
    "Entity",
    "EntityActorConfig",
    "EntityArchiveResponse",
    "EntityEntityType",
    "EntityReference",
    "ExecutedTool",
    "ExecutedToolStatus",
    "ExportProjectQuality",
    "ExportProjectResponse",
    "FileAnalysisMetadata",
    "FileAnalysisMetadataAnalysisLoadingState",
    "FileSource",
    "FileSourceStatus",
    "FileUploadResponse",
    "FileUploadWebhookEventName",
    "FileUploadWebhookPayload",
    "GenerateStoryboardScene",
    "GenerateTextResponse",
    "GetFilesResponse",
    "ImageAssetRequest",
    "ImageModelMode",
    "ListEntitiesResponse",
    "ListProjectsResponse",
    "ListRemixActionsResponse",
    "ProjectExport",
    "ProjectExportStatus",
    "ProjectResponse",
    "ProjectResponseStatus",
    "PronunciationReplacement",
    "RemixAction",
    "RemixActionAddTransitions",
    "RemixActionDisableCaptions",
    "RemixActionEditWithAgent",
    "RemixActionEditWithAgentMode",
    "RemixActionEnableCaptions",
    "RemixActionRun",
    "RemixActionSetBackgroundMusic",
    "RemixActionSetLogo",
    "RemixActionSetLogoPosition",
    "RemixActionStatus",
    "RemixActionType",
    "RemixAction_AddTransitions",
    "RemixAction_DisableCaptions",
    "RemixAction_EditWithAgent",
    "RemixAction_EnableCaptions",
    "RemixAction_SetBackgroundMusic",
    "RemixAction_SetLogo",
    "RemixProjectResponse",
    "RemixTransitionStyle",
    "SceneGeneration",
    "SceneGenerationType",
    "ScriptToVideoRequest",
    "SearchFilesResponse",
    "SearchFilesResult",
    "SlideshowToVideoRequest",
    "StartToolExecutionResponse",
    "StartWorkflowRunResponse",
    "StorageFile",
    "StorageFileScope",
    "StorageFileType",
    "StoryboardToVideoRequest",
    "StoryboardToVideoRequestQuality",
    "ToolExecutionWebhookEventName",
    "ToolExecutionWebhookPayload",
    "ToolSuccessResult",
    "ToolSuccessResultType",
    "TtsVoice",
    "TtsVoiceDisplayGender",
    "TtsVoiceListResponse",
    "VideoAssetRequest",
    "VideoModelMode",
    "VisualPacing",
    "VoiceoverToVideoRequest",
    "WatermarkMode",
    "WebhookEndpoint",
    "WebhookEndpointListResponse",
    "WebhookEventName",
    "WorkflowCaptionBackgroundStyle",
    "WorkflowCaptionBackgroundStyleType",
    "WorkflowCaptionStyle",
    "WorkflowCaptionStyleTextJustification",
    "WorkflowCaptionStyleVerticalAlignment",
    "WorkflowRgbColor",
    "WorkflowRun",
    "WorkflowRunStatus",
    "WorkflowRunWebhookEventName",
    "WorkflowRunWebhookPayload",
    "WorkflowType",
    "WorkflowVisualStyle",
    "WorkflowVisualStyleType",
]
