# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ApiErrorRequirement(UniversalBaseModel):
    """
    What is needed to resolve the error. Present when the error can be fixed by fulfilling a specific requirement (e.g. purchasing an add-on).
    """

    type: str = pydantic.Field()
    """
    Requirement type (e.g. `purchase_add_on`, `upgrade_plan`).
    """

    details: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Key-value pairs with requirement-specific context.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
