# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class AssistantWorkflowSuggestion(UniversalBaseModel):
    """
    A starting-point workflow the assistant suggests for the conversation. Act on it with `POST /v1/assistant/chats/{projectId}/actions/{actionId}` to select the workflow and continue.
    """

    action_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="actionId"),
        pydantic.Field(
            alias="actionId", description="Opaque id to pass to the act-on-action endpoint to select this workflow."
        ),
    ]
    workflow_type: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="workflowType"),
        pydantic.Field(
            alias="workflowType",
            description="Identifier of the suggested workflow (e.g. `SCRIPT_TO_VIDEO`, `SLIDESHOW_TO_VIDEO`). Treat as an opaque label; new workflow types may be added over time.",
        ),
    ]
    title: str = pydantic.Field()
    """
    Short human-readable name of the suggested workflow.
    """

    description: str = pydantic.Field()
    """
    One-line explanation of what this workflow will do.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
