# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .avatar_presenter_displayable_gender import AvatarPresenterDisplayableGender


class AvatarPresenter(UniversalBaseModel):
    """
    An avatar presenter available for video generation.
    """

    avatar_presenter_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="avatarPresenterId"),
        pydantic.Field(
            alias="avatarPresenterId",
            description="Presenter id (e.g. `vg_pres_...`). Pass as `avatarPresenterId` to `POST /v1/tools/generate-avatar`.",
        ),
    ]
    displayable_gender: typing_extensions.Annotated[
        AvatarPresenterDisplayableGender,
        FieldMetadata(alias="displayableGender"),
        pydantic.Field(alias="displayableGender", description="Presenter gender."),
    ]
    image_url: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="imageUrl"),
        pydantic.Field(alias="imageUrl", description="Still image of the presenter."),
    ]
    thumbnail_url: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="thumbnailUrl"),
        pydantic.Field(alias="thumbnailUrl", description="Thumbnail image of the presenter."),
    ]
    preview_video_url: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="previewVideoUrl"),
        pydantic.Field(alias="previewVideoUrl", description="Short preview clip of the presenter speaking."),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
