# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .entity_actor_config import EntityActorConfig
from .entity_entity_type import EntityEntityType
from .entity_reference import EntityReference


class Entity(UniversalBaseModel):
    """
    A reusable actor or visual style. Attach its reference images to workflows for consistent characters and looks.
    """

    entity_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="entityId"),
        pydantic.Field(alias="entityId", description="The entity id (e.g. `vg_enti_...`)."),
    ]
    entity_type: typing_extensions.Annotated[
        EntityEntityType,
        FieldMetadata(alias="entityType"),
        pydantic.Field(
            alias="entityType",
            description="ACTOR features a consistent character; VISUAL_STYLE guides the look of generated images.",
        ),
    ]
    name: str = pydantic.Field()
    """
    Display name.
    """

    description: str = pydantic.Field()
    """
    Optional description. Empty string when not set.
    """

    actor_config: typing_extensions.Annotated[
        typing.Optional[EntityActorConfig],
        FieldMetadata(alias="actorConfig"),
        pydantic.Field(
            alias="actorConfig",
            description="Voice and presenter summary for ACTOR entities. Null for VISUAL_STYLE entities.",
        ),
    ] = None
    references: typing.List[EntityReference] = pydantic.Field()
    """
    Reference images attached to the entity.
    """

    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When the entity was created (ISO 8601)."),
    ]
    updated_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="updatedAt"),
        pydantic.Field(alias="updatedAt", description="When the entity was last updated (ISO 8601)."),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
