# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .api_error import ApiError
from .executed_tool_status import ExecutedToolStatus
from .tool_success_result import ToolSuccessResult


class ExecutedTool(UniversalBaseModel):
    tool_execution_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="toolExecutionId"),
        pydantic.Field(alias="toolExecutionId", description="Execution id matching the original request."),
    ]
    status: ExecutedToolStatus
    tool_type: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="toolType"),
        pydantic.Field(alias="toolType", description="Tool name (e.g. `PROMPT_TO_IMAGE`, `TEXT_TO_SPEECH`)."),
    ]
    results: typing.Optional[typing.List[ToolSuccessResult]] = pydantic.Field(default=None)
    """
    One entry per generated result. Present when `status` is `succeeded`.
    """

    error: typing.Optional[ApiError] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
