# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .export_delivery_destination_type import ExportDeliveryDestinationType


class ExportDeliveryDestination(UniversalBaseModel):
    integration_connection_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="integrationConnectionId"),
        pydantic.Field(
            alias="integrationConnectionId",
            description="Id of the connected integration that will receive this export.",
        ),
    ]
    type: ExportDeliveryDestinationType = pydantic.Field()
    """
    Where to deliver the export within the connected integration.
    """

    slack_channel_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="slackChannelId"),
        pydantic.Field(
            alias="slackChannelId", description="Target channel id. Required when `type` is `slack_channel`."
        ),
    ] = None
    google_drive_folder_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="googleDriveFolderId"),
        pydantic.Field(
            alias="googleDriveFolderId", description="Target folder id. Required when `type` is `google_drive_folder`."
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
