# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ExportProjectResponse(UniversalBaseModel):
    export_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="exportId"),
        pydantic.Field(
            alias="exportId",
            description="Opaque export id. Poll `GET /v1/projects/{projectId}/exports/{exportId}` or subscribe to webhooks for completion.",
        ),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
