# This file was auto-generated by Fern from our API Definition.

import typing

FileAnalysisMetadataAnalysisLoadingState = typing.Union[
    typing.Literal["UNATTEMPTED", "LOADING", "FULFILLED", "REJECTED"], typing.Any
]
