# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .storage_file_ref import StorageFileRef


class ImageAssetRequest(UniversalBaseModel):
    image: StorageFileRef
    num_candidates: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="numCandidates"),
        pydantic.Field(alias="numCandidates", description="Number of output candidates to generate. Defaults to 1."),
    ] = None
    is_output_temporary: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="isOutputTemporary"),
        pydantic.Field(
            alias="isOutputTemporary",
            description="When true, generated files are scoped as temporary. Defaults to false.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
