# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .remix_action_run import RemixActionRun


class ListRemixActionsResponse(UniversalBaseModel):
    remix_actions: typing_extensions.Annotated[
        typing.List[RemixActionRun],
        FieldMetadata(alias="remixActions"),
        pydantic.Field(alias="remixActions", description="Remix actions for the project, most recent first."),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
