# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .api_error import ApiError
from .project_export_status import ProjectExportStatus


class ProjectExport(UniversalBaseModel):
    export_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="exportId"),
        pydantic.Field(alias="exportId", description="Opaque export id matching the original request."),
    ]
    project_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="projectId"),
        pydantic.Field(alias="projectId", description="Id of the exported project."),
    ]
    status: ProjectExportStatus
    progress_percentage: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="progressPercentage"),
        pydantic.Field(
            alias="progressPercentage",
            description="Completion progress for the current attempt (0-100). Always `100` when `status` is `succeeded`.",
        ),
    ]
    attempt_index: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="attemptIndex"),
        pydantic.Field(
            alias="attemptIndex", description="Zero-based index of the current or most recent export attempt."
        ),
    ]
    download_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="downloadUrl"),
        pydantic.Field(
            alias="downloadUrl", description="Signed MP4 download URL. Present when `status` is `succeeded`."
        ),
    ] = None
    thumbnail_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="thumbnailUrl"),
        pydantic.Field(
            alias="thumbnailUrl",
            description="Signed thumbnail URL. Present when `status` is `succeeded` and a thumbnail is available.",
        ),
    ] = None
    error: typing.Optional[ApiError] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
