# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .aspect_ratio import AspectRatio
from .project_response_status import ProjectResponseStatus


class ProjectResponse(UniversalBaseModel):
    """
    Simplified project metadata.
    """

    project_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="projectId"),
        pydantic.Field(alias="projectId", description="Opaque project id (e.g. `vg_proj_...`)."),
    ]
    title: str
    aspect_ratio: typing_extensions.Annotated[
        AspectRatio, FieldMetadata(alias="aspectRatio"), pydantic.Field(alias="aspectRatio")
    ]
    status: ProjectResponseStatus = pydantic.Field()
    """
    High-level project status.
    """

    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    updated_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")
    ]
    project_url: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="projectUrl"),
        pydantic.Field(
            alias="projectUrl",
            description="Deep link to open this project in the VideoGen web editor. Not required for an API-only integration: store `projectId` and use the Projects API (export, remix, metadata). Use `projectUrl` when a person should open the project in the app to review or edit it manually. The project is visible only to members of your team and any project collaborators, the same access model as a project created in the dashboard.",
        ),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
