# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .api_error import ApiError
from .remix_action_status import RemixActionStatus
from .remix_action_type import RemixActionType


class RemixActionRun(UniversalBaseModel):
    remix_action_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="remixActionId"),
        pydantic.Field(alias="remixActionId", description="Opaque remix action id (e.g. `vg_rmix_...`)."),
    ]
    type: RemixActionType
    status: RemixActionStatus
    project_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="projectId"),
        pydantic.Field(alias="projectId", description="Id of the project this remix action edits."),
    ]
    project_url: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="projectUrl"),
        pydantic.Field(alias="projectUrl", description="URL to view the project in the VideoGen app."),
    ]
    progress_percentage: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="progressPercentage"),
        pydantic.Field(
            alias="progressPercentage",
            description="Completion progress for the current attempt (0-100). Always `100` when `status` is `succeeded`.",
        ),
    ]
    attempt_index: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="attemptIndex"),
        pydantic.Field(
            alias="attemptIndex", description="Zero-based index of the current or most recent execution attempt."
        ),
    ]
    error: typing.Optional[ApiError] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
