# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .remix_action_set_logo_position import RemixActionSetLogoPosition
from .remix_action_video_editor_agent_mode import RemixActionVideoEditorAgentMode
from .workflow_caption_style import WorkflowCaptionStyle


class RemixAction_SetBackgroundMusic(UniversalBaseModel):
    """
    A single edit applied to a project. Discriminated by `type`.
    """

    type: typing.Literal["SET_BACKGROUND_MUSIC"] = "SET_BACKGROUND_MUSIC"
    file_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="fileId"), pydantic.Field(alias="fileId")
    ] = None
    volume: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class RemixAction_SetLogo(UniversalBaseModel):
    """
    A single edit applied to a project. Discriminated by `type`.
    """

    type: typing.Literal["SET_LOGO"] = "SET_LOGO"
    file_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="fileId"), pydantic.Field(alias="fileId")
    ] = None
    position: typing.Optional[RemixActionSetLogoPosition] = None
    size_percent: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="sizePercent"), pydantic.Field(alias="sizePercent")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class RemixAction_EnableCaptions(UniversalBaseModel):
    """
    A single edit applied to a project. Discriminated by `type`.
    """

    type: typing.Literal["ENABLE_CAPTIONS"] = "ENABLE_CAPTIONS"
    caption_style: typing_extensions.Annotated[
        typing.Optional[WorkflowCaptionStyle], FieldMetadata(alias="captionStyle"), pydantic.Field(alias="captionStyle")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class RemixAction_DisableCaptions(UniversalBaseModel):
    """
    A single edit applied to a project. Discriminated by `type`.
    """

    type: typing.Literal["DISABLE_CAPTIONS"] = "DISABLE_CAPTIONS"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class RemixAction_VideoEditorAgent(UniversalBaseModel):
    """
    A single edit applied to a project. Discriminated by `type`.
    """

    type: typing.Literal["VIDEO_EDITOR_AGENT"] = "VIDEO_EDITOR_AGENT"
    prompt: str
    mode: typing.Optional[RemixActionVideoEditorAgentMode] = None
    target_duration_seconds: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="targetDurationSeconds"),
        pydantic.Field(alias="targetDurationSeconds"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


RemixAction = typing_extensions.Annotated[
    typing.Union[
        RemixAction_SetBackgroundMusic,
        RemixAction_SetLogo,
        RemixAction_EnableCaptions,
        RemixAction_DisableCaptions,
        RemixAction_VideoEditorAgent,
    ],
    pydantic.Field(discriminator="type"),
]
