# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .aspect_ratio import AspectRatio


class RemixActionResizeProject(UniversalBaseModel):
    """
    Change the project's output aspect ratio (e.g. to a vertical 9:16 social format). The video is re-flowed to the new ratio.
    """

    aspect_ratio: typing_extensions.Annotated[
        AspectRatio, FieldMetadata(alias="aspectRatio"), pydantic.Field(alias="aspectRatio")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
