# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .remix_action_regenerate_images_model_mode import RemixActionRegenerateImagesModelMode


class RemixActionRegenerateImages(UniversalBaseModel):
    """
    Restyle every eligible still image in the project to a new look (image-to-image), replacing each image in place. Eligible images are non-SVG image assets backed by an uploaded or generated file. Runs asynchronously: one restyled image is generated per eligible image. If the project has no eligible images, the action is skipped and completes successfully without changing anything.
    """

    style_prompt: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="stylePrompt"),
        pydantic.Field(
            alias="stylePrompt",
            description='Describe the visual style to apply to every image (e.g. "watercolor painting", "cinematic film still").',
        ),
    ]
    model_mode: typing_extensions.Annotated[
        typing.Optional[RemixActionRegenerateImagesModelMode],
        FieldMetadata(alias="modelMode"),
        pydantic.Field(alias="modelMode", description="Image generation quality tier. Defaults to `STANDARD`."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
