# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .video_quality import VideoQuality


class RemixActionConvertImagesToVideos(UniversalBaseModel):
    """
    Animate every eligible still image in the project into a short AI video clip (image-to-video), replacing each image in place. Eligible images are non-SVG image assets backed by an uploaded or stock file. Runs asynchronously: one clip is generated per image. If the project has no eligible images, the action is skipped and completes successfully without changing anything (for example, a project whose timeline is already all video clips).
    """

    motion_prompt: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="motionPrompt"),
        pydantic.Field(
            alias="motionPrompt",
            description='Describe the motion to apply to every image (e.g. "slow cinematic push-in"). Omit or pass `null` for automatic motion.',
        ),
    ] = None
    mute_output_videos: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="muteOutputVideos"),
        pydantic.Field(
            alias="muteOutputVideos",
            description="Mute the generated clips and suppress generated background music. Recommended when the clips sit behind a voiceover. Defaults to `true`.",
        ),
    ] = None
    quality: typing.Optional[VideoQuality] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
