# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class RemixActionSetBackgroundMusic(UniversalBaseModel):
    """
    Set, replace, or remove the project's background music track.
    """

    file_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="fileId"),
        pydantic.Field(
            alias="fileId",
            description="File id of an uploaded audio file to use as background music (e.g. `vg_file_...`). Upload it first via `POST /v1/files/upload`. Pass `null` to remove the existing background music.",
        ),
    ] = None
    volume: typing.Optional[float] = pydantic.Field(default=None)
    """
    Music volume from 0 (silent) to 1 (full). Omit or pass `null` to keep the current volume.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
