# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .remix_action_edit_with_agent_mode import RemixActionEditWithAgentMode


class RemixActionEditWithAgent(UniversalBaseModel):
    """
    Apply an open-ended, natural-language edit to the project. An editing agent interprets the prompt, makes the changes, validates them, and visually checks the result. Well suited to tasks like replacing placeholder copy with your own text.
    """

    prompt: str = pydantic.Field()
    """
    A natural-language description of the edit to make (e.g. "Replace the headline with 'Summer Sale - 40% off' and update the subtitle to match").
    """

    mode: typing.Optional[RemixActionEditWithAgentMode] = pydantic.Field(default=None)
    """
    Editing strategy. `MINOR_EDIT` (default) makes targeted changes while keeping the structure. `RETHINK` re-storyboards the video: it selects which scenes to keep and their order, then edits each in parallel.
    """

    target_duration_seconds: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="targetDurationSeconds"),
        pydantic.Field(
            alias="targetDurationSeconds",
            description="Optional soft ceiling on the rebuilt video's duration, in seconds. Only used when `mode` is `RETHINK`.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
