# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .aspect_ratio import AspectRatio
from .remix_action import RemixAction
from .workflow_caption_style import WorkflowCaptionStyle


class SlideshowToVideoRequest(UniversalBaseModel):
    file_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="fileId"),
        pydantic.Field(
            alias="fileId",
            description="Opaque file id of an uploaded PDF or PowerPoint file (e.g. `vg_file_...`). Upload the file first via `POST /v1/files/upload`.",
        ),
    ]
    slide_scripts: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="slideScripts"),
        pydantic.Field(
            alias="slideScripts",
            description="Optional per-slide narration, in slide order, applied by index: each slide uses its matching entry, and an empty string makes that slide silent. If you provide fewer entries than slides, the remaining slides are silent; extra entries are ignored. Omit this field entirely to narrate each slide from its speaker notes in the uploaded file. To guarantee no narration on any slide, pass an empty array.",
        ),
    ] = None
    aspect_ratio: typing_extensions.Annotated[
        typing.Optional[AspectRatio], FieldMetadata(alias="aspectRatio"), pydantic.Field(alias="aspectRatio")
    ] = None
    language: typing.Optional[str] = pydantic.Field(default=None)
    """
    Output language as a BCP-47 code (e.g. `en`, `es`, `fr`). Defaults to English.
    """

    voice_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="voiceId"),
        pydantic.Field(
            alias="voiceId",
            description="Voice id from `GET /v1/resources/tts-voices` (e.g. `vg_voic_...`). A default voice is used when omitted. Any voice may be used here, including voices where `supportsDirectToolExecution` is false.",
        ),
    ] = None
    voice_speed: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="voiceSpeed"),
        pydantic.Field(
            alias="voiceSpeed", description="Speech rate multiplier. Defaults to the voice's default speed."
        ),
    ] = None
    avatar_presenter_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="avatarPresenterId"),
        pydantic.Field(
            alias="avatarPresenterId",
            description="Optional avatar presenter id from `GET /v1/resources/avatar-presenters` (e.g. `vg_pres_...`). When set, the narration is delivered by a talking-head presenter avatar. Pass your `voiceId` to that endpoint to list presenters sorted by best match for the voice. Omit for a standard voiceover with no presenter.",
        ),
    ] = None
    caption_style: typing_extensions.Annotated[
        typing.Optional[WorkflowCaptionStyle],
        FieldMetadata(alias="captionStyle"),
        pydantic.Field(
            alias="captionStyle",
            description="Caption styling. Omit to use the default style with captions shown. Pass an object to override individual style fields (any omitted field uses the default). Pass `null` to hide captions entirely.",
        ),
    ] = None
    logo_file_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="logoFileId"),
        pydantic.Field(
            alias="logoFileId",
            description="Optional file id of an uploaded logo image to overlay on the video (e.g. `vg_file_...`). Upload the image first via `POST /v1/files/upload`. Only image files are accepted.",
        ),
    ] = None
    remix_actions: typing_extensions.Annotated[
        typing.Optional[typing.List[RemixAction]],
        FieldMetadata(alias="remixActions"),
        pydantic.Field(
            alias="remixActions",
            description="Optional edits applied to the project after the video is built, in order. Each action runs asynchronously; the response returns one remix action id per action. Captions and a logo are set with the `captionStyle` and `logoFileId` request fields above; recommended remix actions here are `SET_BACKGROUND_MUSIC` for a music bed, `ADD_TRANSITIONS` to stamp transitions between sections and assets, and `EDIT_WITH_AGENT` for open-ended natural-language edits. See the [Remix actions](/remix-actions) guide.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
