# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class StartToolExecutionResponse(UniversalBaseModel):
    """
    Identifier for the in-flight tool execution. Pass `apiTaskExecutionId` back when polling, cancelling, or correlating webhook events.
    """

    api_task_execution_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="apiTaskExecutionId"),
        pydantic.Field(
            alias="apiTaskExecutionId",
            description="Opaque execution id (e.g. `vg_exec_...`). Treat as a single string — do not split it client-side.",
        ),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
