# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class StartWorkflowRunResponse(UniversalBaseModel):
    """
    Returned when a workflow run is accepted. Poll `GET /v1/workflows/runs/{workflowRunId}` or subscribe to webhooks for completion.
    """

    workflow_run_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="workflowRunId"),
        pydantic.Field(alias="workflowRunId", description="Opaque workflow run id (e.g. `vg_work_...`)."),
    ]
    project_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="projectId"),
        pydantic.Field(alias="projectId", description="Id of the project created for this workflow run."),
    ]
    project_url: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="projectUrl"),
        pydantic.Field(alias="projectUrl", description="URL to view the project in the VideoGen app."),
    ]
    remix_action_ids: typing_extensions.Annotated[
        typing.List[str],
        FieldMetadata(alias="remixActionIds"),
        pydantic.Field(
            alias="remixActionIds",
            description="Opaque remix action ids (e.g. `vg_rmix_...`), one per `remixActions` entry in request order. Empty when no remix actions were requested. Each runs after the video is built; poll `GET /v1/projects/{projectId}/remix-actions`.",
        ),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
