# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .file_source import FileSource
from .storage_file_scope import StorageFileScope
from .storage_file_type import StorageFileType


class StorageFile(UniversalBaseModel):
    """
    Metadata for a generated file. Obtain ids from tool results or `GET /v1/files`.
    """

    file_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="fileId"), pydantic.Field(alias="fileId", description="File id (e.g. `vg_file_...`).")
    ]
    type: typing.Optional[StorageFileType] = pydantic.Field(default=None)
    """
    File type. Null when the file is still being processed and the type has not yet been determined.
    """

    scope: StorageFileScope = pydantic.Field()
    """
    File scope.
    
    - `GLOBAL`: user-uploaded or standalone generated files that persist indefinitely.
    - `PROJECT`: project-specific files (e.g. text-to-speech clips in a generated project).
    - `EXPORT`: project exports.
    - `TEMPORARY`: short-lived files guaranteed to be available for 24 hours, after which they may be archived at any time. Not analyzed (no description, transcript, or embedding).
    """

    display_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="displayName"),
        pydantic.Field(alias="displayName", description="Display name for the file."),
    ] = None
    description: typing.Optional[str] = None
    duration_seconds: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="durationSeconds"),
        pydantic.Field(
            alias="durationSeconds", description="Duration in seconds for video and audio files. Null for images."
        ),
    ] = None
    transcript: typing.Optional[str] = pydantic.Field(default=None)
    """
    Transcript text for video and audio files, when available. Null for images or when no transcript has been generated.
    """

    thumbnail_source: typing_extensions.Annotated[
        typing.Optional[FileSource],
        FieldMetadata(alias="thumbnailSource"),
        pydantic.Field(alias="thumbnailSource", description="Thumbnail image source. Populated after hydration."),
    ] = None
    preview_source: typing_extensions.Annotated[
        typing.Optional[FileSource],
        FieldMetadata(alias="previewSource"),
        pydantic.Field(
            alias="previewSource",
            description="Preview rendition source (720p for video, resized for images). Populated after hydration.",
        ),
    ] = None
    download_source: typing_extensions.Annotated[
        typing.Optional[FileSource],
        FieldMetadata(alias="downloadSource"),
        pydantic.Field(
            alias="downloadSource", description="Highest-quality downloadable rendition. Populated after hydration."
        ),
    ] = None
    hls_source: typing_extensions.Annotated[
        typing.Optional[FileSource],
        FieldMetadata(alias="hlsSource"),
        pydantic.Field(
            alias="hlsSource",
            description="Private HLS streaming source. Populated for video and audio files once Mux playback is ready. Uses a signed token; treat like other signed sources.",
        ),
    ] = None
    is_public_preview_enabled: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="isPublicPreviewEnabled"),
        pydantic.Field(
            alias="isPublicPreviewEnabled",
            description="Whether public preview is enabled for this file. When true, `publicHlsUrl` and `publicPlaybackId` are populated.",
        ),
    ] = None
    public_hls_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="publicHlsUrl"),
        pydantic.Field(
            alias="publicHlsUrl",
            description="Public HLS streaming URL. Only present when `isPublicPreviewEnabled` is true. Does not require authentication or signed tokens.",
        ),
    ] = None
    public_playback_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="publicPlaybackId"),
        pydantic.Field(
            alias="publicPlaybackId",
            description="Encoded public playback id (e.g. `vg_play_...`). Pass this to the `@videogen/player` or `@videogen/player-react` packages. Only present when `isPublicPreviewEnabled` is true.",
        ),
    ] = None
    source_tool_type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="sourceToolType"),
        pydantic.Field(
            alias="sourceToolType",
            description="Tool type that generated this file (e.g. `PROMPT_TO_IMAGE`, `TEXT_TO_SPEECH`). Only present when the file was created by a tool execution.",
        ),
    ] = None
    source_tool_execution_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="sourceToolExecutionId"),
        pydantic.Field(
            alias="sourceToolExecutionId",
            description="Execution id of the tool call that generated this file (e.g. `vg_exec_...`). Only present when the file was created by a tool execution.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
