# This file was auto-generated by Fern from our API Definition.

import typing

ToolExecutionWebhookEventName = typing.Union[
    typing.Literal["tool_execution.succeeded", "tool_execution.failed", "tool_execution.cancelled"], typing.Any
]
