# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .aspect_ratio import AspectRatio
from .remix_action import RemixAction
from .visual_pacing import VisualPacing
from .workflow_caption_style import WorkflowCaptionStyle
from .workflow_visual_style import WorkflowVisualStyle


class VoiceoverToVideoRequest(UniversalBaseModel):
    file_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="fileId"),
        pydantic.Field(
            alias="fileId",
            description="Opaque file id of an uploaded voiceover audio file (e.g. `vg_file_...`). Upload the file first via `POST /v1/files/upload`.",
        ),
    ]
    aspect_ratio: typing_extensions.Annotated[
        typing.Optional[AspectRatio], FieldMetadata(alias="aspectRatio"), pydantic.Field(alias="aspectRatio")
    ] = None
    visual_style: typing_extensions.Annotated[
        WorkflowVisualStyle, FieldMetadata(alias="visualStyle"), pydantic.Field(alias="visualStyle")
    ]
    visual_pacing: typing_extensions.Annotated[
        typing.Optional[VisualPacing], FieldMetadata(alias="visualPacing"), pydantic.Field(alias="visualPacing")
    ] = None
    language: typing.Optional[str] = pydantic.Field(default=None)
    """
    Output language as a BCP-47 code (e.g. `en`, `es`, `fr`). Defaults to English.
    """

    caption_style: typing_extensions.Annotated[
        typing.Optional[WorkflowCaptionStyle],
        FieldMetadata(alias="captionStyle"),
        pydantic.Field(
            alias="captionStyle",
            description="Caption styling. Omit to use the default style with captions shown. Pass an object to override individual style fields (any omitted field uses the default). Pass `null` to hide captions entirely.",
        ),
    ] = None
    logo_file_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="logoFileId"),
        pydantic.Field(
            alias="logoFileId",
            description="Optional file id of an uploaded logo image to overlay on the video (e.g. `vg_file_...`). Upload the image first via `POST /v1/files/upload`. Only image files are accepted.",
        ),
    ] = None
    workflow_agent_context: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="workflowAgentContext"),
        pydantic.Field(
            alias="workflowAgentContext",
            description="Optional production notes for the AI that builds the video — visual direction for how to illustrate the voiceover (e.g. on-screen code or text to display, specific b-roll to feature, or scene-by-scene staging). Never spoken; does not change the uploaded voiceover audio or its transcript.",
        ),
    ] = None
    remix_actions: typing_extensions.Annotated[
        typing.Optional[typing.List[RemixAction]],
        FieldMetadata(alias="remixActions"),
        pydantic.Field(
            alias="remixActions",
            description="Optional edits applied to the project after the video is built, in order. Each action runs asynchronously; the response returns one remix action id per action. Captions and a logo are set with the `captionStyle` and `logoFileId` request fields above; recommended remix actions here are `SET_BACKGROUND_MUSIC` for a music bed, `ADD_TRANSITIONS` to stamp transitions between sections and assets, and `EDIT_WITH_AGENT` for open-ended natural-language edits. See the [Remix actions](/remix-actions) guide.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
