# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .tool_execution_webhook_event_name import ToolExecutionWebhookEventName


class WebhookEndpoint(UniversalBaseModel):
    endpoint_id: typing_extensions.Annotated[str, FieldMetadata(alias="endpointId"), pydantic.Field(alias="endpointId")]
    url: str
    events: typing.List[ToolExecutionWebhookEventName]
    description: typing.Optional[str] = None
    created_at: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(
            alias="createdAt", description="Seconds since epoch (Unix timestamp) when the endpoint was created."
        ),
    ]
    signing_secret: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="signingSecret"),
        pydantic.Field(
            alias="signingSecret",
            description="HMAC secret for verifying [Standard Webhooks](https://www.standardwebhooks.com/) signatures. Only returned once on create; store it securely.",
        ),
    ] = None
    signing_secret_last4: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="signingSecretLast4"),
        pydantic.Field(
            alias="signingSecretLast4", description="Last four characters of the signing secret, for display purposes."
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
