# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .workflow_caption_background_style_type import WorkflowCaptionBackgroundStyleType
from .workflow_rgb_color import WorkflowRgbColor


class WorkflowCaptionBackgroundStyle(UniversalBaseModel):
    """
    Background drawn behind caption text.
    """

    type: WorkflowCaptionBackgroundStyleType = pydantic.Field()
    """
    RECT draws one rectangle behind the whole line; WRAPPED hugs the text; WORD_BY_WORD draws a box per word.
    """

    background_color: typing_extensions.Annotated[
        WorkflowRgbColor, FieldMetadata(alias="backgroundColor"), pydantic.Field(alias="backgroundColor")
    ]
    border_radius_proportion: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="borderRadiusProportion"),
        pydantic.Field(
            alias="borderRadiusProportion",
            description="Corner rounding as a proportion of the background height (0 = square corners).",
        ),
    ] = None
    opacity_proportion: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="opacityProportion"),
        pydantic.Field(alias="opacityProportion", description="Background opacity from 0 (transparent) to 1 (opaque)."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
